### ISSUE TITLE
Leave blank to use the default Category label function is not working

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1032]
On Applications forms when you add a category the label field in the form states that "Leave blank to use the default Category label". This does not work.

If you in the Application form set labels they are rendered as they should. But if left blank the default labels do to show up.

**Comment by ankitjavalkar** [comment]
I tried replicating the issue. However it seems this is now working as expected. The name of the category is displayed if the label field for the category block is kept blank. This issue can be closed.

**Comment by frjo** [comment]
Yes, this works now. Closing.
