### ISSUE TITLE
Add a generate random password option when creating a new user, as a replacement to putting a password in

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1082]
When creating a new user,  add a "send password over email"  option

**Comment by frjo** [comment]
Better to send them a password reset link. that will force them to set there own password before they can use the account. And it avoid having passwords send in plain text.

**Comment by danblah** [comment]
Why do we have to add a password at all when creating a new user? I don't want to set or see the password. I want to create a new user, not be asked or required to put in a password, and have it send them the password reset (or ideally a create password for new account) email.

**Comment by saoun** [comment]
so, expected behavior:

- new user submits an application (having put it their email address)
- after submitting an application, user receives email saying their application was submitted, and a link to create a new password

**Comment by frjo** [comment]
@saoun This is how it works today when you submit an application.

This issue is about user accounts created manually by staff.

**Comment by saoun** [comment]
I see, makes sense now!

**Comment by Parbhat** [comment]
@frjo Looks like the issue is about creating users from Wagtail admin. Is it?

**Comment by frjo** [comment]
@Parbhat Yes it is.
