### ISSUE TITLE
Create unique slack channel for comment notifications

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1161]
- Account name or name of person: Di 
- Title of submission (app URLs alone are OK): Create unique slack channel for notes

**Is your feature request related to a problem? Please describe.**
It is difficult for team members to review notes from an internal review when they did not attend the meeting. There is no indication or easy way to find out which submissions were discussed and outcomes of these discussions when notes are submitted in the webapp. 

**Is your feature request related to an existing functionality? Please describe.**
Team currently receives notifications in Slack when a new note has been submitted within webapp. This "notify" channel is insufficient because it is crowded with other notifications. 

**Describe the solution you'd like**
lease create a separate and unique slack channel for notes. A separate channel would give team members a better understanding of which notes have been drafted and when these notes were submitted. This is at least a two step process: 1) Create a separate and unique slack channel for notes 2) Redirecting notifications about notes towards a NEW slack channel.

**Describe alternatives you've considered**
The alternative is rewriting a summary of these notes in a googledoc.

**Additional context**
Notes written in googledoc were easy for staff to find and review when they missed a meeting. It's more difficult to locate these notes within the webapp.

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff

**Ideal deadline**
End of April or early May

**Comment by frjo** [comment]
Next time, please remove the placeholder text so the issue only contains your own text. Keeping it all make the issue hard to decipher.

Is this the notifications that read "A new private|internal comment has been posted on …"?

You can already set a custom slack channel for each Fund. Maybe that can be used, creating less busy channels where staff members can ping the one or two funds they are interested in?

**Comment by fourthletter** [comment]
Yes, it's "A new private comment has been posted on..." 

Perhaps we could set aside time to discuss alternative solutions this Friday morning. Thanks!

**Comment by fourthletter** [comment]
#notes on slack is a unique channel for "A new private|internal comment has been posted on …"? 

This channel will display only internal comments.

**Comment by danblah** [comment]
I'd suggest having a flag for "meeting notes" that can be checked when submitting a new comment. when checked, the notification includes changes to include "@lead: A new team comment (#MeetingNotes) has been posted on [project title](/apply/submissions/5555/#communications) by <commenter>".  At that point, someone who wanted to search "in:#notify on:today #MeetingNotes" in slack for any notes today or on:yesterday for notes yesterday or on:mm-dd-yyyy for notes from a specific day.

**Comment by fourthletter** [comment]
I'm raising up this issue because another fund needs a unique slack channel. Perhaps we can discuss a long-term solution for managing manager's specific communication needs?

**Comment by frjo** [comment]
Fund can already have their own channels. Go and edit a fund and you find a slash channel field at the bottom.

When using it you need to set up the channel in Slack yourself *and* add the "WebApp" tp the apps section of the channel in Slack.

The "WebApp" bot is the thing that push messages from Django to Slack.
