### ISSUE TITLE
Make the "last updated" date in submission/all table be the last commented date if it's later that submission last updated.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1177]

**Comment by danblah** [comment]
Would be nice if there could be a separator/grouping automatically inserted into the list to show what was discussed on a specific day

**Comment by fourthletter** [comment]
Related to #269

**Comment by danblah** [comment]
If we follow https://github.com/OpenTechFund/opentech.fund/issues/1161, only those submissions with "Meeting Notes" checked would show up here, sorted newest to oldest.

**Comment by frjo** [comment]
I have changes this issue to make it a lot simpler but hopefully solve the same problem.

**Comment by Parbhat** [comment]
@frjo Got a rough idea what needs to done from issue title. Can you please add more details?

**Comment by frjo** [comment]
Submission have comments (activity) under the comments tab. Get the date from the latest one.

If that date is newer than submission last updated use it for sorting.

But looking at the code it looks like this is already in place. Can you take a look at it and confirm the current functionality?

https://github.com/OpenTechFund/hypha/blob/5337ba51f4349776ec385e4a24fbb8be04e545fa/hypha/apply/funds/tables.py#L54-L62

https://github.com/OpenTechFund/hypha/blob/5337ba51f4349776ec385e4a24fbb8be04e545fa/hypha/apply/funds/models/submissions.py#L146-L152

**Comment by Parbhat** [comment]
@frjo Thanks for details. Tested and confirmed the functionality is already present.
