### ISSUE TITLE
Give reviewers access only to submission that have reached an "AC review" state or higher

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1182]

**Comment by danblah** [comment]
Does this mean a submission that has been in the state "AC review" or higher, that has reviewer reviews, with a final state of dismissal would not be visible to the reviewers? We would like submissions visible, regardless of the final outcome, to all reviewers.

**Comment by frjo** [comment]
New criteria: Reviewers can view all submissions that have reached an "AC review" state or higher.

Is that correct?

**Comment by danblah** [comment]
Yes, regardless of whether they were a reviewer at the time it was promoted (ie, a reviewer added later to a fund/lab should still have access to the submissions in that fund/lab that reached "AC review" state or higher before they where known to the system).

**Comment by danblah** [comment]
They should be able to see all of this in /apply/submissions as we do, but only those as defined above.

**Comment by sks444** [comment]
Hi @frjo, wanted to confirm few things:

Along with showing the list of submissions which are higher than "AC review" state for reviewers at /apply/submission, are we also planing to show the `By Status` table? If yes, I think we would be only showing the last four columns in the table?

Also I am guessing that reviewers should not be shown with `STAFF ASSIGNMENTS` , `REVIEWS` , and `RESULTS` buttons.

<img width="1366" alt="Screenshot 2020-07-08 at 3 19 18 PM" src="https://user-images.githubusercontent.com/22263040/86910729-c6bf2880-c137-11ea-840d-0500d2dbacce.png">

**Comment by frjo** [comment]
@sks444 Reviewers do not have access to "SubmissionOverviewView" (/apply/submissions/), that is for staff only.

Reviewers do have access to "SubmissionReviewerListView" (/apply/submissions/all/). This one should be filtered down to only the ones they have access to, as it is now.

**Comment by sks444** [comment]
Thanks for clarifying that @frjo.

>They should be able to see all of this in /apply/submissions as we do, but only those as defined above.

@danblah comment here lead me believe that we are planning to open `/apply/submissions` also for reviewers to list down all the submissions which has reached "AC review" state or higher. 

So currently at `/apply/submissions/all/` reviewers are shown with only the submission they have [submitted review for](https://github.com/OpenTechFund/hypha/blob/8acb9ca904128b0e131e5fad09772a4dee4d0f73/hypha/apply/funds/views.py#L332). But now we are planning to show all the submissions which has reached "AC review" state or higher even if the reviewer has not submitted review to those submissions.

Although in this case reviewer is going to `/apply/submissions/all` by clicking on the `show all` at the dashboard which says `Your previous reviews`, showing a list with submission where they have not reviewed might be a little misleading. That is where I also thought showing that list `/apply/submission` might be a good idea.

**Comment by frjo** [comment]
@sks444 We might want to go this route but for this PR I think we should stick with limiting reviewers to submission that have reached an "AC review" state or higher and have not been dismissed.

As of now reviewers can see all submission they are assigned to. We want to limit that to the ones they are assigned to and that have reached an "AC review" state etc.

**Comment by sks444** [comment]
Thanks @frjo.

>As of now reviewers can see all submission they are assigned to..

So to confirm I think you meant `reviewed` by `assigned to`, as reviewers can only see all the submissions which are [reviewed by them](https://github.com/OpenTechFund/hypha/blob/8acb9ca904128b0e131e5fad09772a4dee4d0f73/hypha/apply/funds/views.py#L332) at `/apply/submissions/all`. But now we want to limit that list to the submissions which are in "AC review" state or higher and not in dismissed state.

**Comment by danblah** [comment]
Having a hard time following whats happening here.

I want to flag that this is an implementation specific need for OTF that others may not share (for example, Reset). 

I don't currently know what OTF wants. This is what Reset wants:

* All applications that have been in state AC Review or higher to be viewable in submissions/all by reviewers.
* This includes any application from any lab/fund, regardless of whether or not the reviewer is associated/assigned those aplications.
* This is regardless of final outcome (dismmsed, approved, or undetermined).

**Comment by frjo** [comment]
@sks444 You are correct, the submissions they are assigned too but has not yet reviewed show up on their dashboard.

But Dans comment show that we need to make this in to settings. Maybe three settings in wagtail admin like below.

Reviewer settings:

* Reviewers should see
    * A. All submissions 
       B. Only submissions they review.
    * A. All states
       B. Only AC Reviewers and higher
    * A. All outcomes
       B. Only accepted

**Comment by frjo** [comment]
After discussions with OTF and Reset we remove this part from the issue "and have not been dismissed".

So reviewers should see all submission that have reached "AC review" state or higher.

**Comment by frjo** [comment]
For future flexibility I'm thinking if it would be good to add a flag on each submission that sets reviewers visibility.

**Comment by sks444** [comment]
@frjo, having a Reviewer settings that you mentioned is a good idea to give flexibility and avoid any confusions. 

It would be good to have it in the admin for now and if we see we need more flexibility, we can also add it in the ui for each submission. Adding another parameter in the ui may create extra confusions if we do not always need it.

So to summarise, the upcoming changes will change the output of `submissions/all` for reviewers based on the settings parameters and everything else should be same as it is now.
