### ISSUE TITLE
Child pages of Labs incorrectly show a "CLOSED" header, where there should be nothing.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1245]
See https://www.opentech.fund/labs/legal-lab/for-lawyers/ as an example.

**Comment by frjo** [comment]
Current example https://www.opentech.fund/labs/legal-lab/

**Comment by ankitjavalkar** [comment]
This is happening when the RFP Page does not have an Application Type, Django template IF conditions ```page.is_open``` fails in the ```fund_apply_cta.html``` which causes the CLOSED to show up.

Is it usually the case that the RFP Page does not have a linked/populated application_type field?

A possible solution could be that I can implement a new template without the If-Else checks and hence the CLOSED does not show up. I can also try to check if the page is an RFP page and then skip the if-else conditions altogether.

Any suggestions?

**Comment by frjo** [comment]
@saoun @fourthletter https://www.opentech.fund/labs/legal-lab/for-lawyers/ also show closed now. Is that correct?

**Comment by ankitjavalkar** [comment]
@frjo https://www.opentech.fund/labs/legal-lab/ currently does not show closed. 

The original example cited in the issue does show closed - https://www.opentech.fund/labs/legal-lab/for-lawyers/ . "for-lawyers" is the RFP in this case.

CC @saoun @fourthletter
