### ISSUE TITLE
Visible for users in the role Staff, create a "Reviewer leaderboard" over AC reviewers

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1250]
Columns are:
* Reviewer
* Total
* 90 days
* This year
* Last year
* Most recent (date, links to most recent review if possible)

Allow sorting by those and the following filters:
* Funds
* Rounds
* Reviewers

Related to https://github.com/OpenTechFund/opentech.fund/issues/1249

**Comment by frjo** [comment]
@danblah Should this be a top ten list or what number of reviewers should show?

If you want to show all I do not think it's a good idea to put in on the dashboard. To heave to load and takes up a lot of space. Better to then to have it on a separate page.

**Comment by tmsndrs** [comment]
Hey @danblah I wonder if this would make more sense to be added to 'Submissions' tab. Just thinking of the additional content we're going to be adding to the dashboard in the next few sprints. My view is that the dashboard should be the place OTF staff can come to to see what's on their plate. The submissions tab is where you get an overview of everything that's happening with applications.

**Comment by saoun** [comment]
For all users in the role Staff and Reviewer, it should also show the total number of reviews ever submitted, the total number of reviews submitted this calendar year, and the total number of reviews submitted the previous calendar year

**Comment by saoun** [comment]
@tmsndrs yes, agree for this to be in submission tab. 

Also, is there a status on this?

**Comment by rudietuesdays** [comment]
Note to self and @harumhelmy : Optimize via #1351

**Comment by frjo** [comment]
See https://test-apply.opentech.fund/apply/submissions/reviews/

There you can click each name to see a list of that persons reviews.

Should reviewers be able see all this?

**Comment by frjo** [comment]
New version at https://test-apply.opentech.fund/apply/submissions/reviews/

* Only list reviewers, no staff.
* Only visible to staff.

**Comment by saoun** [comment]
This looks great!

Could we change the title from Review Leaderboard to AC Reviews instead?

And in the Submissions banner here https://test-apply.opentech.fund/apply/submissions/, can we rename it to "AC Reviews" instead of just "Reviews" ?

**Comment by frjo** [comment]
AC is OTF specific so I would prefer a more generic term. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
