### ISSUE TITLE
Improvements to 2FA workflow and UI

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1256]
1. The code input field is a weird box that if i hit the small up or down arrows, raises or lowers the number. Can we remove that for just a text field?
2. On the completion page (https://test-apply.opentech.fund/account/two_factor/setup/complete/) where it says "Congratulations, you've successfully enabled two-factor authentication.", can we add a sentence that says be sure to generate and download backup codes, in case you loose your device (https://test-apply.opentech.fund/account/two_factor/backup/tokens/).
3. On the https://test-apply.opentech.fund/account/two_factor/backup/tokens/, can we bump the "Back to Account Security" to be under the "Generate tokens" button?
4. Can we get a #notify when someone enables or disables 2fa?

**Comment by saoun** [comment]
is there anything holding this up @frjo ?

**Comment by frjo** [comment]
No, it just needs to get done.

**Comment by frjo** [comment]
This is on test for testing. Moved back button to top, made sure field to enter 2FA code has focus when needed, improved styling. Added button to get back to account page.

**Comment by fourthletter** [comment]
Go to 2FA Link: https://test-apply.opentech.fund/account/two_factor/setup/

**Design specifications are visible, how do we test if it's functional?** 

Image 1:
![image](https://user-images.githubusercontent.com/20019656/78145605-1686a900-73ff-11ea-85a6-c01027e5b84d.png)

Image 2:
![image](https://user-images.githubusercontent.com/20019656/78145703-34eca480-73ff-11ea-8202-4dee0243144f.png)

**Comment by frjo** [comment]
@fourthletter Do the steps a user setting up 2FA would do and make sure it works and that it’s easy to understand each step. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
@frjo 1) In the **Backup Tokens**, clicking on **Show Codes** gives me to an error 2) I've logged out and logged back in, but the system didn't ask me 2FA. I'm fine with these features going live. Thank you!

**Comment by saoun** [comment]
hey @frjo, can we tweak the CSS on this a bit? 

- change 'Enable Two-Factor Authentication' (image 1,2,3 from Di) to match the font size of "profile" and "become" on the account page. 
- change 'Account Security' (image 4) to the same font size as well.
- change 'Backup Tokens' from the backup token page tot he same font size as well. 
- reduce font size of 'Backup Tokens' and 'Disable Two-Factor Authentication' on account security page (image 4) and make sure they are the same size. 
- add the same banner 'welcome xxx' that shows on the account page, to the account security page as well
- delete 'back to account' button (image 4) and instead maybe add it in the banner that will be added
- delete the "back" button on the second page (image 2 from Di)
