### ISSUE TITLE
Tasks needed when git repo renamed to "hypha"

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1277]
[Renaming a repository - GitHub Help](https://help.github.com/en/articles/renaming-a-repository)

> When you rename a repository, all existing information, with the exception of Project Pages URLs, is automatically redirected to the new name, including:
> 
>  * Issues
> * Wikis
> * Stars
> * Followers
> 
> In addition to redirecting web traffic, all git clone, git fetch, or git pushoperations targeting the previous location will continue to function as if made on the new location. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL.
> 
> Since a few years GitHub will set up redirects when renaming a repository so most things should just work. But it's highly recommended to update any links etc.
> 
> Git repo links exist on the following services:

* Heroku (main hosting)
* Sentry
* Scout
* CircleCI
* TravisCI
* Cloudflare access (or is that just organisation?)

All developers should be alerted so they can do:

    git remote set-url origin git@github.com:OpenTechFund/hypha.git

**Comment by Parbhat** [comment]
Are we renaming the repo?

**Comment by frjo** [comment]
@Parbhat Yes, OTF want to have a name for the app that is not OTF specific. Do not now if they have come up with a good name for the app yet. If you have suggestions please ping them, know they have been thinking about it for some time.

**Comment by saoun** [comment]
adding @maxpearl here too

**Comment by frjo** [comment]
This is now done

Developer might want to run:

`git remote set-url origin git@github.com:OpenTechFund/hypha.git`

but GitHub set up aliases when renaming repos so stuff seems to just work.
