### ISSUE TITLE
Account cleanup

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1281]
To clean up the user account for the site:

* Mark account inactive that has not logged in after 3 month.
* Delete accounts that has not logged in and have no submissions.

**Comment by danblah** [comment]
Should we move this to the otf issue repo @frjo?

**Comment by saoun** [comment]
Looks good. For a user who has no submission and has not logged in in over 3 months

**Comment by frjo** [comment]
Both commands are in place but only the inactivate one is running for now.
