### ISSUE TITLE
Add id's to the section elements on fund, lab, and submissions so that users can link directly to them 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1285]
Use the form id's or whatever is easiest to insert id's into the section elements. On hover/mouse over show a dim [icon](https://thenounproject.com/search/?q=link) that a user can click/hold and copy the url for.

**Comment by Parbhat** [comment]
@frjo I think the issue refers to section headings like "Basic information", "More information about your project" and "Legal information for the contract" on Fund say [Rapid Response Fund](https://apply.opentech.fund/rapid-response-fund/). It currently uses `Section text/header` block which is a Richtext field. I would be easier if we can use new blocks for headings like these sections called [HeadingBlock](https://github.com/wagtail/bakerydemo/blob/20fdd22226c5e2861f5f8a6317569230ca606700/bakerydemo/base/blocks.py#L57). As we will have direct control on heading HTML being rendered (can add ids). In Richtext we do not have direct control on rendered HTML.

**Comment by frjo** [comment]
@Parbhat Yes, splitting "Section text/header" in to one "Section text" that works like now and one "Section header" where staff can enter plain text and pick a header level 2-6 sounds good. Then easy to add the id anchor stuff.
