### ISSUE TITLE
Make it possible to have required fields in file groups

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1294]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24120%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/OpenTechFund/opentech.fund/issues/1294)

When a required field is in a field group make it unrequired when the field group is closed.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $120.00)

- [<img src='https://avatars1.githubusercontent.com/u/620336?v=4' alt='danblah' width=24 height=24> danblah](https://issuehunt.io/u/danblah) ($20.00)
- [<img src='https://avatars1.githubusercontent.com/u/53949652?v=4' alt='resetnetwork' width=24 height=24> resetnetwork](https://issuehunt.io/u/resetnetwork) ($100.00)

### Submitted pull Requests
- [#2153 Required attribute in field groups](https://issuehunt.io/r/OpenTechFund/hypha/pull/2153)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/OpenTechFund/opentech.fund/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by fourthletter** [comment]
Thank you, please release this feature.
