### ISSUE TITLE
Project detail view: Create project page 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1327]
- [x] On the application submission there is a link to this page within a new 'project' side bar block at the top of the list 
- [x] Side bar block is only visible when there is a project associated with the submission 
- [x] Create skeleton page with key information (information copied from application submission, dummy page layout content) 
- [x] On successful creation I am redirected to the new project page
- [x] QA complete

**Comment by abigail-hampson** [comment]
Looks good to me

**Comment by abigail-hampson** [comment]
Hello, 

This is now ready to be tested against the acceptance criteria above. If you view a submission page with a project page you should be able to view the links in the side bar, and the skeleton project page is created. 

Thanks, 
Abigail

**Comment by fourthletter** [comment]
The last two acceptance criteria failed during test: 1) Create skeleton page with key information and 2) On successful creation I am redirected to the new project page

1) Create skeleton page with key information
Test worked for this test submission: https://test-apply.opentech.fund/apply/submissions/5/
Test failed for these 2 test submission: https://test-apply.opentech.fund/apply/submissions/26/ AND https://test-apply.opentech.fund/apply/projects/5/

2) On successful creation I am redirected to the new project page
After creating a new project, I was not redirected to the new project page for any of the new projects I created. 

Thanks,
Di

**Comment by todd-dembrey** [comment]
@fourthletter Thanks DI. Turns out there was an issue with projects of labs. I've made a fix here: #1403 and will redeploy soon

**Comment by abigail-hampson** [comment]
Looks good, works with labs for me

**Comment by fourthletter** [comment]
It brings me no joy to inform you that two (2) projects are created after a proposal has been 'accepted.'

Example1 from IFF: https://test-apply.opentech.fund/apply/submissions/79/
Example2 from Lab: https://test-apply.opentech.fund/apply/submissions/84/

Image: 
<img width="366" alt="Screen Shot 2019-09-04 at 6 56 53 AM" src="https://user-images.githubusercontent.com/20019656/64249416-90929600-cee1-11e9-9bbe-9d0302260e5c.png">

**Comment by saoun** [comment]
@todd-dembrey is this done? can we close?

**Comment by saoun** [comment]
@abigail-hampson updates? can we close?

**Comment by peteandrew** [comment]
I've looked in to this and I wasn't able to replicate the reported bug. In a local environment, when a submission is accepted, only one project is created. In the test environment I couldn't find any submissions with multiple projects. I think this is ready to be closed.
