### ISSUE TITLE
Send to compliance 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1334]
- [x] Project approval will trigger an event about sending to compliance when the project is approved 
- [x] Sent in the form of an email
    - [x] Lead contact details is included in the email 
    - [x] Simplified views included in email - #1399, #1372 
- [x] Project is moved to contracting state 
- [x] Date of sending is tracked on the model and added to the simplified project page

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional. Thanks! :boom:

**The lead was not included in the email**

![image](https://user-images.githubusercontent.com/20019656/69345913-e7d21800-0c3f-11ea-8d2f-53e959f6aa46.png)

**Comment by todd-dembrey** [comment]
@fourthletter the content of the email is as follows:

```
A Project is awaiting your review.

Title: {{ source.title }}
Link: {{ request.scheme }}://{{ request.get_host }}{% url 'apply:projects:detail' pk=source.pk %}

Please contact {{ source.lead }} - {{ source.lead.email }} if you have any questions.
```

Upon review i can see that the wrong path is currently being sent to compliance, i will update that.
