### ISSUE TITLE
Dashboard OTF Staff: Dashboard - Update project table 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1340]
Projects linked 

- [ ] Includes the following fields, 
title 
status 
fund 
end date 
fund allocation 
- [ ] Maximum of 10 items 
- [ ] Default sorted by last activity date 
- [ ] Filtered by projects i am lead on

**Comment by ghickman** [comment]
@todd-dembrey – Should this table be orderable?

**Comment by todd-dembrey** [comment]
Not yet. That is part of #1424 - we need a list view to work with.

The pattern we use is:
* Here is a list of relevant recent items - there aren't that many.
* if you try and filter or order them we will take you to the page which has the complete list on because you were probably looking for one that isnt listed..

**Comment by fourthletter** [comment]
[ ] The default was NOT sorted by last activity date, but by END DATE.
[ ] Project table as NOT filtered by projects I am lead on.

fred's view:
![image](https://user-images.githubusercontent.com/20019656/64723366-67a07100-d49e-11e9-95c0-de28933a18a2.png)

dee's view:
![image](https://user-images.githubusercontent.com/20019656/64723402-78e97d80-d49e-11e9-86d0-f4aecdd8861b.png)

**Comment by todd-dembrey** [comment]
@fourthletter I've checked on test and this seems to not be the case anymore. Projects on the Dashboard are filtered by lead.

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional. Thanks! 💥

**Comment by todd-dembrey** [comment]
Latest update from @fourthletter is accepted - why is this in the backlog?

**Comment by saoun** [comment]
can this be deployed then? @todd-dembrey @frjo

**Comment by todd-dembrey** [comment]
The changes have been merged and deployed as part of 1.20.0 

https://github.com/OpenTechFund/hypha/releases/tag/v1.20.0
