### ISSUE TITLE
Project Detail document upload: Select from submission

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1342]
- [x] New link to "select a document"
- [x] A new modal 
- [x] Allows selecting of document from submission radio widget 
- [x] A copy of the document is made when "uploaded"
- [x] Same behaviour and permissions as the upload view

**Comment by fourthletter** [comment]
This hurts me more than it hurts you. I am NOT able to use the upload function for 1) https://test-apply.opentech.fund/apply/projects/1/ , 2) https://test-apply.opentech.fund/apply/projects/3/ , and other submissions in the **_committed_** stage.


![image](https://user-images.githubusercontent.com/20019656/64735760-354f3d80-d4b7-11e9-8c60-b67edc67bf55.png)

**Comment by todd-dembrey** [comment]
There was an issue with the id between the two uploads being shared. This was fixed in #1578

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional during test. Thanks! :boom:

**Comment by todd-dembrey** [comment]
The changes have been merged and deployed as part of 1.20.0 

https://github.com/OpenTechFund/hypha/releases/tag/v1.20.0
