### ISSUE TITLE
Uploading Contract 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1378]
Contracts will be uploaded to the system by both Clients and OTF Staff. We will track all contracts that are uploaded to the system in order to facilitate the creation of contract amendments.
- [x] When a Contract is uploaded to the system it can be marked as signed or unsigned.
- [x] When a Client uploads a contract it will always be considered signed.
- [x] OTF Staff must confirm that the contract is signed before the Project can progress.
- [x] When an OTF Staff member uploads a contract they can mark it as signed or unsigned (default being unsigned) to facilitate emailing of contracts.
- [x] The Client will be notified about the upload in both situations
- [x] If the contract is signed it is considered as approved by the Lead (uploader) and the project will progress.
- [x] All signed Contracts will be accessible within app in the sidebar in date descending order
- [x] If there is a newer unsigned contract than the last signed contract this should be visible

**Comment by fourthletter** [comment]
As an 'applicant' I was able to submit a contract, but this document was not visible or accessible in the project page. As a 'lead,' I was not able to see the contract uploaded by the applicant.

[ ] Go to https://test-apply.opentech.fund/apply/projects/8/#activity-feed
[ ] See Activity Feed as evidence that applicant has uploaded a contract
[ ] Contract submitted by applicant is unavailable in project page :(

![image](https://user-images.githubusercontent.com/20019656/64985364-b1200000-d892-11e9-9c32-0eec9f950825.png)

**Comment by todd-dembrey** [comment]
@fourthletter Thanks for the feedback - We do not track all contracts in the sidebar. If a user uploads a newer contract we consider any old unapproved or unsigned contracts to be invalid and do not have any valid actions.

I've made some changes to the activity feed to better track versions of the contract - these are now linked on the activity for new activities and will also track the state of the contract when uploaded.

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional during test. Thanks! 💥

**Comment by todd-dembrey** [comment]
The changes have been merged and deployed as part of 1.20.0 

https://github.com/OpenTechFund/hypha/releases/tag/v1.20.0
