### ISSUE TITLE
Payment request - OTF review and actions 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1381]
Uses modal workflow - button to "update" Payment request
- [ ] Applicants can delete 
     * only in the submitted or changes request status
- [ ] Staff can reject, request change, accept, paid 
     - [ ] Reject moves to the "rejected" status
         - [ ] Cannot move out of "rejected"
     - [ ] Request change moves to the "changes requested" state 
         - [ ] "reject" only at this point
     - [ ] Accept moves to the "under review" status 
        - [ ]  You can only transition from "under review" to "paid"
     - [ ] Paid moves to the "Paid" status 
          - [ ] No further transitions

**Comment by fourthletter** [comment]
Is it possible for staff to have control over when they can reject, request change, accept a request at any point regardless of status? 

Example:

- [ ] Staff can reject, request change, accept, paid 
     - [ ] Reject moves to the "rejected" status
     - [ ] Staff can move out of "rejected" 
- [ ] Request change moves to the "changes requested" state 
         - [ ] "reject" only at this point
         - [ ] "accept" when requested changes are complete
- [ ] Accept moves to the "under review" status 
        - [ ]  You can only transition from "under review" to "paid"
        - [ ]  You can only transition from "under review" to "reject"
        - [ ]  You can only transition from "under review" to "accept"
        - [ ]  You can transition from "accept" to any status
- [ ] Paid moves to the "Paid" status 
          - [ ] No further transitions
          - [ ] Staff can move out of "Paid" status into a different status
