### ISSUE TITLE
Payment request - edit 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1382]
- [x] When a payment request is in the submitted state it is editable by staff and applicant 
- [x] When a payment request is in the change requested state it is editable only by applicant 
- [x] There is an activity when a payment request is edited 
- [x] When a payment request is edited by the applicant, staff are notified by slack 
- [x] When a payment request is edited by staff, staff are notified by slack 
- [x] When a payment request is edited by staff the applicant is notified by email 
- [x] Deleting a receipt is un checking a checkbox

**Comment by todd-dembrey** [comment]
This has been merged and deployed as part of release v1.20.0

https://github.com/OpenTechFund/hypha/releases/tag/v1.20.0
