### ISSUE TITLE
Make it possible to add reminders to submissions

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1491]
The UI can be similar to how meta categories works.

* A button that open a popup to add new reminders.
* Each reminder has a data and an action.
* Reminders show in a block in the sidebar. Sort in decending date order, expired deadlines becomes gray.
* Staff can delete reminders.

The following actions should be available.

* Reminder to Staff, sends out a Slack notice
* Reminder to Reviewers, sends out an e-mail
* Reminder to Applicants, sends out an e-mail

List upcoming reminders on users Dashboard.

**Comment by danblah** [comment]
Can we also include this with the coming projects type that TB is finishing up on the current sprints?

**Comment by Parbhat** [comment]
Slack discussion about the issue

> fredrik  3:27 PM
> I think Torchbox has some kind of remider feature in the things they are building for project handling, see the test and sprint branches. Maybe something we can build out/make use of. https://github.com/OpenTechFund/opentech.fund/issues/1623
> 
> parbhat  3:31 PM
> Thanks, Is reminders are sent on a specific event or admin user enter a datetime when creating reminders? (edited) 
> 
> fredrik  3:31 PM
> datetime
> 
> 3:32
> So staff should be able to set up any number of remiders for any future date. When the date is reached an action is run.
> 
> parbhat  3:33 PM
> It will need a celery task which runs daily like scheduling pages.
> 
> fredrik  3:33 PM
> What actions that are needed is not clear yet. But I know one they need, remind reviewers to review.
> 
> 3:33
> So we can start with that one and prepere the code so it’s easy to add more actions.
> 
> 3:34
> At the start all actions will be sending e-mails I believe, but some might send Slack notifications as well.
> 
> 3:36
> We already use "Heroku Scheduler” to run things like "$ django-admin publish_scheduled_pages"
> 
> parbhat  3:36 PM
> Reminder modal will have date on which reminder needs to be sent, action type (remind reviewers to review). Do we also need to get additional data?
> 
> fredrik  3:39 PM
> Reminders are tied to a submission so that needs to be included.
> 
> parbhat  3:39 PM
> yeah, that is included in the backend. I am thinking about fields presented to the admin user in reminders modal popup. (edited) 
> 
> fredrik  3:40 PM
> Then only date and action type is needed.

**Comment by frjo** [comment]
Ready for testing on test. The E-mail will not be actually sent bur please test the UI.

**Comment by fourthletter** [comment]
I hit a glitch during the test. I get this message 'Please enter a valid date' when I click on the create button:

![image](https://user-images.githubusercontent.com/20019656/77684332-39810b00-6f70-11ea-885e-13a2811796fc.png)

**Comment by Parbhat** [comment]
From the screenshot, time needs to be entered as well.

**Comment by fourthletter** [comment]
The features were visible and functional during test. 💥 

✔️ A button that open a popup to add new reminders.
✔️ Each reminder has a data and an action.
✔️ Reminders show in a block in the sidebar. Sort in decending date order, expired deadlines becomes gray.
✔️ Staff can delete reminders.

Final Result:

![image](https://user-images.githubusercontent.com/20019656/77762141-70f2c480-700f-11ea-86c8-2b6200277489.png)
