### ISSUE TITLE
Error in the submissions-by-round-react-app

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1527]
When adding new comments in the editor a error popups on submit. But when the page is reloaded the comment has been saved.

![65056989-e0407b00-d93f-11e9-82fc-877d2f8cf597](https://user-images.githubusercontent.com/191392/65143018-44cd0a00-da14-11e9-876b-520add67b91f.png)

**Comment by harumhelmy** [comment]
Hi @Parbhat and @vaibhavmule, if you haven't started on this yet I'd love to take a first try at it! Let me know :)

**Comment by frjo** [comment]
@harumhelmy Please take this on.

**Comment by Parbhat** [comment]
@harumhelmy Sure.
