### ISSUE TITLE
Edit Note Section in Detailed View

### ISSUE THREAD

**Issue by saoun** [OpenTechFund/hypha#1528]
**For Testing**: https://test-apply.opentech.fund/apply/rounds/824/?submission=81

**Describe the bug**
UI issue: in Note section in detailed view: When clicking on "Edit," it's very hard to tell that the place to edit is the submit box, as opposed to the comment box (where the comment already is). Everything greys out and it looks like the page freezes.

Is it possible to make the edit within that comment box itself where the comment already is, as opposed to sending the user back to the submit box? It would be way more intuitive.

**To Reproduce**
Go to 'detailed view'
Click on 'Notes'
Add a comment
Click on 'Edit'

**Expected behavior**
Would be better if the Editing UI was more intuitive. Right now, hard to tell that it sends you back to the lower 'submit' box rather than being able to edit directly in the comment itself. 

**Priority**
Low priority

**Affected roles**
Staff

**Comment by harumhelmy** [comment]
Hi! Working on this now.
