### ISSUE TITLE
Rename main app from "opentech" to "hypha"

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1544]
What is needed to rename the main app from "opentech" to "hypha". A lot of imports and file path will need to be updated.

Any special things that we need to think about?

**Comment by frjo** [comment]
@Parbhat Any tips around this app renaming?

**Comment by Parbhat** [comment]
@frjo Looks like only import paths and project settings like [this](https://github.com/OpenTechFund/opentech.fund/blob/436a5e6b331108f639ceb9ba80a862997e4d8857/opentech/settings/base.py#L14) will need updates. Old migration files will also need updates for newer installs.

**Comment by saoun** [comment]
@maxpearl I believe you are working on this too? adding you here
