### ISSUE TITLE
Rebuild determination forms to be staff created with stream fields 

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1562]
They should work the same as review forms. Staff can create them and on each fund select which one to use for each stage, just like reviews.

- [x] All current determinations need to be migrated to the new format. 
- [x] The current "Determination" and "Determination message" fields (first two) should be required on all new determinations forms.
- [ ] Make it possible to set default answer for "Determination message".

**Comment by saoun** [comment]
@Parbhat do you have a time frame for this? I'm trying to organize some of these issues

**Comment by Parbhat** [comment]
@saoun I had a chat with @frjo about the priority of this issue. Looking to pick it in Q2 as will give the team some time to learn more about custom stream fields forms in our code.

**Comment by fourthletter** [comment]
@bumbleblue Per our conversation about determinations, this feature would rebuild determinations forms so they would work as review forms. Any feedback would be greatly appreciated. ❤️

**Comment by fourthletter** [comment]
I can't attach this form to an existing round or fund within WagTail. 

![image](https://user-images.githubusercontent.com/20019656/87050852-d3419080-c1cc-11ea-8237-2785c3bd05e8.png)

**Comment by frjo** [comment]
@fourthletter Go to e.g. https://test-apply.opentech.fund/admin/pages/729/edit/ and there you find this button.

![determination-form](https://user-images.githubusercontent.com/191392/87055850-26373a00-c205-11ea-8cf6-39de229e36eb.png)

**Comment by frjo** [comment]
You can only add forms etc. to Funds, not rounds.

Rounds inherit from the fund.

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional. Thank you!
