### ISSUE TITLE
Can't change applicant details in proposals

### ISSUE THREAD

**Issue by tarakiyee** [OpenTechFund/hypha#1576]
**Describe the bug**
Can't change name/email/legalname/address etc. in a proposal 

**To Reproduce**
1. Go to proposal
2. Click edit
3. Change name/email 
4. Click submit
5. Nothing changes

**Expected behavior**
Would like to be able to edit the applicant details section of a proposal as staff, including legal name, address and phone number which don't appear in the edit tab of a proposal 

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff

**Comment by frjo** [comment]
These values are synced with the users account. If they need to be changed do it on the account. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
Related to #663
