### ISSUE TITLE
Add migration to update regions on all submissions

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1581]
Most regions just need renaming, see issue #1173.

The following three regions needs to be updated on all submissions where they are applied.

- North Asia and Russia (Archive) -> Eastern Europe
- Andean (Archive) -> Southern America
- Southern cone (Archive) -> Southern America

**Comment by frjo** [comment]
@danblah @fourthletter Can we simply replace the old archived region with the new one or is there a need to keep the archived region on the submissions as well?

**Comment by frjo** [comment]
Lets replace them.

**Comment by fourthletter** [comment]
We need to hold this issue until there a clear methodology for renaming regions.

**Comment by saoun** [comment]
@fourthletter is there an update on this?
