### ISSUE TITLE
Editing old blog posts with images causes the images to disappear once updated

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/hypha#1610]
**Describe the bug**
For example I edited a word on an old post like this one (https://www.opentech.fund/news/fy18-budget-update/ / https://apply.opentech.fund/admin/pages/774/edit/) and the post originally had a few graphs. They were deleted once I re-published. I then realized the same thing happened on a few other blog posts.

**To Reproduce**
1. Go to an old blog post with images
2. Make any edit (not touching the images, can just be a copy edit)
3. hit publish
4. the images have disappeared

**Expected behavior**
For the images to remain 

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff
- General public

**Comment by frjo** [comment]
I assume this was some hiccup or something so closing. Please reopen if the problem pop up again.
