### ISSUE TITLE
Add setting for page size, used for PDFs

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1669]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saoun** [comment]
@frjo what does this mean?

**Comment by frjo** [comment]
US Letter vs A4 when creating PDFs. People in US expect US letter but the rest of the world uses A4.

At the moment US Letter is hardcoded, I want to add a setting so the size easily can be changed.

**Comment by Parbhat** [comment]
@frjo Which part of the application this issue refers to where we create PDFs? Or Is it related to Old drupal site as mentioned in related issue https://github.com/OpenTechFund/hypha/issues/796?

**Comment by frjo** [comment]
@Parbhat See "ProjectDetailPDFView" and "SubmissionDetailPDFView".
