### ISSUE TITLE
Partners should no longer be able to write reviews

### ISSUE THREAD

**Issue by tarakiyee** [OpenTechFund/hypha#1687]
**Describe the bug**
Partners/Applicants should not be able to view Staff/AC Reviews, not even listed on the side of the application

**Expected behavior**
Just need to check that only Staff/AC members can see the little box that says reviews and what's under it in terms of staff/AC reviews/ 

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Applicants
- Reviewers

**Comment by frjo** [comment]
@tarakiyee @fourthletter  Applicants should not see the review block at all. Do you have examples where one do? When I test they do not see anything.

Partners see the same thing as reviewers, and they can write reviews as well. This is how the specification for this feature stated it should work. If this was a mistake or the need have changed we need to update this.

1. Do OTF want to change so parters do not see the list of existing reviews?
2. What exactly should they see?
3. Should they still be able to write reviews? Then they at least need to see their own reviews I think.

Neither partners or reviewers can view other reviews (unless they are specifically marked "public"), but they can see them in the list in the review block in the sidebar of submission pages.
