### ISSUE TITLE
Copy clone round in Wagtail admin error

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1691]
IntegrityError
duplicate key value violates unique constraint "funds_roundform_pkey"
DETAIL:  Key (id)=(n) already exists.

**Comment by fourthletter** [comment]
I cloned a round in the Wagtail admin. The clone does not appear in the Wagtail Admin, but it appears in the test submission page: https://test-apply.opentech.fund/apply/rounds/861/

**Comment by frjo** [comment]
@fourthletter The round you created has no dates, a start date is required for the filter to work.

**Comment by fourthletter** [comment]
Thank you for clarifying. The test worked!
