### ISSUE TITLE
Add some stream field values to submission csv export

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1704]
* Country (part of address field)
* Have you ever applied to or received funding as an OTF project? (yes/no)
* How long will it take? (x weeks/month)
* Project status (category question)
* Region (category question)
* Country (category question)

**Comment by saoun** [comment]
this is to aid for the dataviz @frjo ?

**Comment by frjo** [comment]
No, this is an export from the DB to a CSV file that staff can open as a spreadsheet. I have build a script/command that can do this and it was a which that more information was included.
