### ISSUE TITLE
Unable to create project approval form

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1729]
- Any personally identifying information: I once shot a man in Reno

**Describe the bug**
Approval Form in Projects does not automatically generate a form.

**To Reproduce**
1. Go to 'Projects' then 'Approval Form'
2. Click on 'create'
3. See error

**Expected behavior**
The approval form or PAF should be generated automatically. This form should contain auto-populated information from proposal.

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff

**Comment by frjo** [comment]
@fourthletter  You have not created any approval form templates yet, I believe that is the cause of the error. Could have been an better error message.

Go to wagtail admin -> Manage -> Project Approval Form and create as many templates as needed.

**Comment by fourthletter** [comment]
@frjo I don't have a "Manage" section in my wagtail admin page.

**Comment by frjo** [comment]
Other users that need that role?

**Comment by fourthletter** [comment]
I created a PAF in the wagtail admin but the PAF could not be created for some projects. The PAF is available for some projects, but not others.

**Comment by frjo** [comment]
I assume this has been solved.
