### ISSUE TITLE
Show a users group/role next to the name

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1735]
This would help everyone easily see who is an applicant/reviewer/staff etc.

**Comment by frjo** [comment]
@saoun We have the following groups/roles:

* Applicant
* Community reviewer
* Partner
* Reviewer
* Staff

Should we show these directly or replace them with some variants? (Team instead of Staff e.g.?)

**Comment by saoun** [comment]
What is the difference between reviewer and community reviewer?

**Comment by frjo** [comment]
You can see the related issues here: https://github.com/OpenTechFund/opentech.fund/issues?utf8=✓&q=is%3Aissue+cfp+

Unsure if this ever has been used since it was deployed nearly a year ago.

**Comment by saoun** [comment]
can we delete "community reviewer" since it seems to not be utilized? would it be easy to re-add if needed?

if we can safely eliminate that, then let's do it and we simplify the roles we have.

**Comment by frjo** [comment]
The role is tied to other functionality so we can't delete just it. But if the community review functionality is not needed/wanted in any form we can clean it out completely from the system.

**Comment by saoun** [comment]
Let's leave it then for now, and revisit deleting it later. It's not actively used right now, but may be in the next few months. 

In the meantime, let's continue with this role indication.
