### ISSUE TITLE
Submission stat page

### ISSUE THREAD

**Issue by saoun** [OpenTechFund/hypha#1740]
Some type of leaderboard or stat page for AC members, which could include some of the following info

[number of reviews from users]: Total number of application reviews from you
[average rating from user reviews]: Your average application rating (on a scale of 0 to 5)
[total number of reviews]: The total number of application reviews
[total number of submission responses]: The total number of submission responses sent to applicants
[total number of concept notes] / [total number of proposals] / [total number of approved proposals]: That's the total number of concept notes received / proposals received / and proposals accepted to date
[total number of pending applications]: Total number of pending applications
[total number of dismissed applications]: Total number of applications we've dismissed :-/
[sum of amount field in all approved applications / sum of amount field in all applications]: That's the total amount of money we've awarded / and the total amount of funds requested of us in USD

Could be related to this: https://github.com/OpenTechFund/opentech.fund/issues/1250

**Comment by frjo** [comment]
@saoun "submission responses" is that comments on the submissions?

**Comment by saoun** [comment]
i think this was copied from an old Blah comment, so you can ignore as im not sure what it refers to either.

**Comment by frjo** [comment]
See https://test-apply.opentech.fund/dashboard/ for staff and reviewers.

**Comment by saoun** [comment]
this is specifically for the view as an AC member right? Not as staff

**Comment by frjo** [comment]
I added it for staff as well bit yes, mostly for reviewers. Easy to remove for staff but thought it might be interesting. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saoun** [comment]
Looks great, thanks @frjo.

Question: in the "submission" box, the numbers refer to submission to funds managed by that specific staff member?

**Comment by frjo** [comment]
@saoun No, it's the sum total number/amounts in all cases.

**Comment by frjo** [comment]
Move to top of Result page.

**Comment by fourthletter** [comment]
- This is the relevant part of the list I shared, can't remember where I shared it
- Show total of how many results a search or filter has returned
- Show page numeration on bottom of search/filter
- Allow to filter for “empty/unassigned” filter
- “Active” applications view or negative filters e.g. please show everything except "denied" applications.
- Not shared before but desired
- Save filter for later use
- https://uxplanet.org/how-to-improve-advanced-search-ux-450df698004c
- certainly the number of applicants and amount requested make sense to me
- if we're using the annual report as a guide, the range of amounts being requested i.e. if you want to see how many applications were submitted for 150-300K
- I also found the median amount to be a more accurate reflection than the average amount fwiw
- not sure how much we want to integrate here vs add to the data viz 2.0

**Comment by fourthletter** [comment]
I recommend changing the default filter to the highest reviews submitted "90 days." As a user this would give me the information I need when I visit this dashboard rather than adjust the filter every single time.

**Comment by frjo** [comment]
@di Made a separate issue for your last comment. https://github.com/OpenTechFund/hypha/issues/2022
