### ISSUE TITLE
Enable staff role to view draft determinations

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1759]
- Any personally identifying information: I am everywhere, yet nowhere

**Is your feature request related to a problem? Please describe.**
The staff role is currently able to view draft determinations. We often provide each other feedback. It is possible if a user is an "admin," but not possible if this user is "staff or team" role.

I want to add this github issue, but it's not urgent. I would like to take more stock in what extra features should be added to the team role moving forward.

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff

**Comment by Parbhat** [comment]
@fourthletter Just to confirm, by _team_ role mentioned in the issue description you mean Group with the name "Team Admin".

**Comment by frjo** [comment]
@Parbhat Fixed the title now. It's the staff role (STAFF_GROUP_NAME/is_apply_staff()) that should see drafts.

**Comment by Parbhat** [comment]
@frjo Thanks

**Comment by sks444** [comment]
@frjo, a staff user is already able to view the draft determination submitted by other staff user.

**Comment by frjo** [comment]
@sks444 You are correct, closing this issue.

@di This is already in place spot closing. Please add a new issue if it was something else you where after.
