### ISSUE TITLE
Wysiwyg editor creating incorrect relative URLs

### ISSUE THREAD

**Issue by saoun** [OpenTechFund/hypha#1764]
1- Here: https://apply.opentech.fund/apply/submissions/5544/reviews/5948/

In this review, there is a link under the section "goals and principles." When you click on the link, it doesn't lead you the actual page. Instead, it compounds the link to the URL the page is already on. 

2- Also here: https://www.opentech.fund/results/supported-projects/delta-chat/

On the Github link (from icon), it redirects again to a relative link instead of the actual URL.

**Comment by frjo** [comment]
1. The link function in the wysiwyg editor seems to have a serious bug. (One of many reasons I prefer Markdown)
2. For gitHub you should only enter the project or organisation, not the complete URL. So "deltachat" and not "https://github.com/deltachat/". This at a minimum needs a help text, or better yet code that handle both cases transparently.

**Comment by saoun** [comment]
Still not working on my end. Same behavior occurs.

**Comment by saoun** [comment]
Having trouble re-creating this bug. 

When I copy over the link from the case above (#1), the same errors happens. That's because the actual URL (if you copy link) is different than the URL displayed (if you copy the text of URL).

But when I test by adding any other link, the issue does not appear.

**Comment by frjo** [comment]
The fix will now correct existing links, but new ones will be correct.

Existing links needs to be manually corrected unfortunately.

The bug only effects internal links, i.e. links within the apply web site.
