### ISSUE TITLE
As an applicant, ability to submit collaborative applications with multiple people/entities

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#177]
- [ ] Create an "Add collaborators" section in Basic info for Concept notes and Proposals
- [ ] For each click, add new Name and Email fields
- [ ] Create an "This is a collaborative submission" check at the end of Basic Info for Concept Notes (link to what that means).
- [ ] Create a function that deletes draft concept notes w/o validated users after 30 days, or draft concept notes w/o any activity in the last 30 days
- [ ] Allow revisions and save as draft, for all validated (non-staged) users, and allow other collaborators to be added after
- [ ] Option to require all applicants to "sign off" on the application before it can be submitted for OTF team review
- [ ] Send determination msgs or any other notifications to all applicants, including invite for proposal msgs
- [ ] Copy editors from the concept note to a proposal when invited
- [ ] Option to require all applicants to "sign off" on the proposal before it can be submitted for OTF review
- [ ] Somehow add a filter (maybe a state?) that allows OTF team to see collaborative applications still in draft

**Comment by fourthletter** [comment]
Related to #324

**Comment by saoun** [comment]
Consolidating this here
https://github.com/OpenTechFund/opentech.fund/issues/524#issuecomment-470737242

**Comment by georgiamoon** [comment]
Yes! thanks @saoun. I tried searching, but wasn't finding the right things.

**Comment by saoun** [comment]
related to https://github.com/OpenTechFund/hypha/issues/1878
