### ISSUE TITLE
403 Error while updating an application

### ISSUE THREAD

**Issue by saoun** [OpenTechFund/hypha#1783]
From a PM: When they initiate sending a determination (like when I update status to dismiss or request more info), they get this instead of the determination screen

![Screenshot 2020-02-05 at 4 47 48 PM](https://user-images.githubusercontent.com/11432628/73886628-fa6bee80-4837-11ea-984e-521cc16f1d01.png)

Just had a similar issue while trying to add a partner to a submission. After selecting a partner, then clicking on "Update," I was redirected to that same error. After refreshing the page, I was led back to the previous status (partner not added), added the partner again, clicked on "Update," and it worked.

**Comment by frjo** [comment]
@saoun I can not recreate this in my local environment with any type of user (admin/staff/reviewer).

* Is it a consistent problem or does it pop up now and then?
* Is it on some particular submissions you get it or just random?
* When did the problems start to occur?

**Comment by saoun** [comment]
@frjo 
- it happened to me once + a PM 2/3 times
- random submissions
- it happened for the first time yesterday for both me + PM

**Comment by frjo** [comment]
I leave this as a temporary CludFlare or Heroku issue that has been fixes. IF not please reopen or create a new issue.
