### ISSUE TITLE
Automatic update status from screening to internal review doesn't always work

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1793]
**Describe the bug**
Connected to Automatically update status on submission when reviewers are added #1251 

An application should automatically move from  'Screening' to 'Internal Review' after TWO reviewers have signed up, the current behavior is that this automation occurs after only one reviewer has signed up. 

gihub issue #571 did not clearly state that two (2) reviewers should be signed up before moving from 

Test application shows status automatically moved from Screening to Internal Review after one reviewer signed up: https://test-apply.opentech.fund/apply/submissions/127/

**Comment by frjo** [comment]
Count only staff reviewers and when there are two of them move the submission to internal review.

**Comment by fourthletter** [comment]
Acceptance criteria visible and functional during test. Thank you! 💥
