### ISSUE TITLE
Address information in the project approval form should not be mandatory

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1808]
**Is your feature request related to a problem? Please describe.**
Please do not require address information in the project approval form. The address section is important to have, but the categories within this section should not be mandatory.

**Priority**
 Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff

**Comment by frjo** [comment]
In PR #1813 I have fixed a bug that made the address field not work properly on the application project form. It should dynamically update when one change country since each country has different address formats but the needs js and css was not loaded. A bug fixed be the PR.

**Comment by fourthletter** [comment]
@frjo It sounds like you've identified the problem and know how to resolve the issue. I'll wait until #1813 is done. Thank you.

**Comment by saoun** [comment]
is this working now that the PR is closed? @fourthletter @frjo

**Comment by frjo** [comment]
If the address field on projects should not be required we first need to make changes to the address field itself.

Different countries has different address items that are required, we need to make the form validation override that in the case the address field itself is not required.

But we want them to work if the user do fill in an address so we are sure it's complete. Unsure how to make this happen.
