### ISSUE TITLE
Update test suite and make more robust

### ISSUE THREAD

**Issue by rudietuesdays** [OpenTechFund/hypha#1832]
**Is your feature request related to a problem? Please describe.**
A number of tests exist inside the codebase, however they are scattered among folders and a number of them fail or error out. We need to refactor the way tests are organized, and get them all green.

**Is your feature request related to an existing functionality? Please describe.**
Yes, a number of tests exist already.

**Describe the solution you'd like**
We will continue using Django Unittests to build out tests, while updating and adding to the existing ones.

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Developers

**Ideal deadline**
Less of a deadline, more of a task to continue working on as we familiarize with the codebase.

**Comment by rudietuesdays** [comment]
On first run of the current tests, a number of tests fail due to the url path for Webpack's stats is looking for a dev file (`webpack-stats.json`) but seeing a prod file (`webpack-stats-prod.json`). Need to investigate updating the `Gulpfile` or running tests in dev mode.

**Comment by frjo** [comment]
@rudietuesdays In the file `.circleci/config.yml` you can see how the test are run in our CI. There is a separate settings file for test, use them by adding `--settings=hypha.settings.test` to the test command.

Other good arguments to the test command are `--parallel` and `--keepdb`.

**Comment by saoun** [comment]
hey @rudietuesdays @harumhelmy any progress on this?

**Comment by todd-dembrey** [comment]
I've added the notes on testing to the #1719 which will be on the [testing page](https://github.com/OpenTechFund/hypha/wiki/Testing) of the wiki

it seems that the issue related to webpack-stats.json has been resolved with the changes to the #1827 where we no longer use the whitenoise for staticfiles in testing. But it would be great to get someone else to confirm this.
