### ISSUE TITLE
Project Management can not upload additional documents

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1846]
Users could upload supporting documentation to initiate projects. However, users are no longer able to upload documentation to support the project moving forward. 

**Step 1: Initial project start**
![image](https://user-images.githubusercontent.com/20019656/76322422-beee9500-62b9-11ea-9161-1829dbab60cc.png)

**Step 2: After project has been initiated, staff is unable to upload additional documentation** 
![image](https://user-images.githubusercontent.com/20019656/76322364-ac745b80-62b9-11ea-9ca0-5efd081298c2.png)

**Comment by frjo** [comment]
Is this not supposed to be done in the reports they send in every week or month?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
@frjo the "supporting documents' section is for financial documents relating to the contract. Report functions are for activities related to the progress of a project.

**Comment by frjo** [comment]
This can now be tested on test. I have removed the checks that only unlocked/editable projects have uploads links.

Please test it out in the workflow of a project and see if it works as it should.

**Comment by fourthletter** [comment]
Test is functional! Please release. Thank you.
