### ISSUE TITLE
User unable to send need more information determination in Ready for Determination status

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1849]
[ ] Go to https://test-apply.opentech.fund/apply/submissions/208/
[ ] Application is currently in "Ready for Determination" status
[ ] Select either 'Add Determination" or 'Update Status' to move the application forward or send out a determination. 
[ ] The options are to either accept or dismiss. Users need to revert back in order to send 'Need more information' determinations. 

User can NOT select "Need More Information" or "Required More Information" in the "Ready for Determination" status.

<img width="582" alt="Screen Shot 2020-03-11 at 11 15 36 AM" src="https://user-images.githubusercontent.com/20019656/76432930-017fa280-638a-11ea-9ed4-e2d36ae10c3f.png">

**Comment by frjo** [comment]
Is this not a duplication of the issue you just tested and approved?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
@frjo It's related. The last GitHub issue was about reverting the workflow status to the previous one. This issue is for applications in the "Ready for Determination" status to send accept, dismiss, and **need more information/required more information**

If you go to this test application, the application is in "Ready for Determination," but staff can not send "required more information." Staff can only send dismiss or accept: https://test-apply.opentech.fund/apply/submissions/208/

**Comment by frjo** [comment]
@fourthletter From the state 'Ready for Final Determination' it's not possible in any of the workflows to move to 'More information required'. It never has.

The word "Final" to me indicates a yes/no decision.

If more info is needed I do not think OTF should move the application this far in the workflow.

You do have the option to move it back to a state where you can ask for more info.

I feel we need to take a thorough look at the current workflows. They do not seem to have much relation to how you work in real life. There must have been some confusion between Torchbox and OTF when this was decided.

**Comment by fourthletter** [comment]
It would be clear if we change "Ready for Determination" status name to "Ready for Final Determination" on the workflow.

**Comment by frjo** [comment]
We are looking at the workflow in whole in other issues so slowing this.
