### ISSUE TITLE
"Social image" feature doesn't work

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/hypha#1850]
**Describe the bug**
For news articles, there is an option under the "Promote" tab to select a "Social image" for "social networks." If it's safe to assume that this is meant to show up in links shared on Twitter for example, it doesn't work

**To Reproduce**
See these tweets for example: 
1) https://twitter.com/OpenTechFund/status/1234592818741547011 
1a) See the selected "social image" under Promote tab/Social Networks here: https://apply.opentech.fund/admin/pages/1128/edit/#tab-promote
2) https://twitter.com/OpenTechFund/status/1232716638270693377
2a) https://apply.opentech.fund/admin/pages/1125/edit/#tab-promote

**Expected behavior**
The selected image should appear within the embedded link (where you see a little paper icon in the tweets linked above)

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- General public

**Comment by frjo** [comment]
Sounds like a bug, will look in to it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
The root url was added for images hosted on s3 so the path became:

~~~~
https://www.opentech.fundhttps://public.opentech.fund/images/image….png
~~~~

And that does not work. Added a check "is_stored_locally".
