### ISSUE TITLE
HMW offer filtered views that can be saved and shared amongst the team?

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1858]

**Comment by fourthletter** [comment]
Related to #269 

[] Staff could use this feature to create one link for review calls.
[] Submissions in different states could be compiled. Example: A revised proposal, concept note, or comment could be grouped together.
[] The detailed view does not provide an easy method for reviewing items in different stages. Example: A revised proposal, concept note, or comment could be grouped together.
[] Submissions are easier to read when they're grouped together.
[] Staff will NO longer need to change the status of a particular application several times back and forth during the course of several weeks. The state "Ready for Discussion" is significant for the workflow status and not a designation for review calls.
