### ISSUE TITLE
Detailed View in WebApp is not functioning

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1862]
Please go to https://test-apply.opentech.fund/apply/rounds/732/

Click on the right button for the detailed view: 
![image](https://user-images.githubusercontent.com/20019656/76956977-5f147180-68eb-11ea-944b-064141ee231d.png)

No submissions are available.

**Comment by frjo** [comment]
@fourthletter Need a bit more to be able to investigate.

**Comment by fourthletter** [comment]
@frjo I provided additional details above. Thank you.

**Comment by frjo** [comment]
The react app is not running for some reason, will investigate.

**Comment by frjo** [comment]
@fourthletter  My bad. A setting on Heroku was not updated when we deployed the API versioned path. Fixed now.
