### ISSUE TITLE
Better date and time formats, and use them consistently.

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1869]
Django has the option to set default formats for date and time.

Now the ISO standard, i.e. 2020-03-20, is used everywhere. It is an international standard, for short dates there are few options if everyone is going to understand them.

When there is room I think we could use a longer form that still is clear to everyone. I suggest the following.

DATE_FORMAT = 'N j, Y' # Mar. 30, 2020
DATETIME_FORMAT = 'N j, Y, H:i' # Mar. 30, 2020, 13:00
SHORT_DATE_FORMAT = 'Y-m-d' # 2020-03-20
SHORT_DATETIME_FORMAT = 'Y-m-d H:i' # 2020-03-20 13:00

The short forms is used in tables and other places where space is a premium.

The long form where there is place.

What do you think?

**Comment by frjo** [comment]
Other option for the long formats:

DATE_FORMAT = 'j F Y' # 30 Mars 2020
DATETIME_FORMAT = 'j F Y, H:i' # 30 Mars 2020, 13:00

**Comment by saoun** [comment]
DATE_FORMAT = 'N j, Y' # Mar. 30, 2020
SHORT_DATE_FORMAT = 'Y-m-d' # 2020-03-20

those look good
