### ISSUE TITLE
Add countdown & deadline on application pages

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1870]
Add to the top of applications a countdown with deadline for when the application must be submitted.

**Comment by frjo** [comment]
@Parbhat The date show up on e.g. the pages https://www.opentech.fund/funds/ and https://www.opentech.fund/funds/internet-freedom-fund/.

But not on the application form itself e.g https://apply.opentech.fund/internet-freedom-fund-2020/

**Comment by Parbhat** [comment]
@frjo Should we only display deadline date on the application forms? Or Also add a countdown timer about how many months, days, hours etc are left.

**Comment by frjo** [comment]
@saoun Do OTF want only the deadline date similar as the the other pages that show it or also a countdown?

I think a simple deadline date is best, the n it looks the same on all pages.

**Comment by saoun** [comment]
simple deadline date is good. no need for a countdown, so much added stress!
