### ISSUE TITLE
Hyperlinks should open in new windows from the Application form

### ISSUE THREAD

**Issue by georgiamoon** [OpenTechFund/hypha#1872]
**Is your feature request related to a problem? Please describe.**
During recent user interviews, users raised frustrations and challenges related to writing in the application form directly. One of those issues is that some of the hyperlinks on the page open in the same window (e.g. in the intro paragraph) and some open in a new tab. 

**Is your feature request related to an existing functionality? Please describe.**
https://apply.opentech.fund/internet-freedom-fund/

**Describe the solution you'd like**
This behavior should first and foremost be consistent, and ideally given that users will be entering information into the form, hyperlinks from the form page should open in a new window as the default behavior.

**Priority**
Low priority

**Affected roles**
- Applicants
- General public

**Ideal deadline**
When possible!

**Comment by saoun** [comment]
@frjo can we assign this to someone? seems like a quick / easy fix

**Comment by frjo** [comment]
I have a PR for this that can be tested on test now.

I made it so all external links (links starting with `https://`) in the Wagtail admin editor gets a target blank so the open in a new tab/window.

I also set target bank to the default for the TineMCE editor that are used on all application forms. Users can select target when they add a link but it's safe to assume that 99% use the default. (Developers call it the tyranny of the default.)

So make all the help and guide links on the applications forms external link and they will open in a new tab/window.

**Comment by saoun** [comment]
note: to make this the default only on the apply site, not the public facing site.

**Comment by frjo** [comment]
Change the implementation to only work on application forms. Now all links, internal and external, on application forms open in a new window/tab.

The main menu and the footer links are not affected, only links on the form itself.

**Comment by fourthletter** [comment]
This feature works like a dream. 🌝
