### ISSUE TITLE
Bad links on the IFF Application page

### ISSUE THREAD

**Issue by georgiamoon** [OpenTechFund/hypha#1873]
**Describe the bug**
At the bottom of the IFF Application page there are two broken links:
- `Read our mission, values, and principles.` goes to: `https://about/program`
- `Terms and Privacy policy.` goes to `https://tos/`

**To Reproduce**
1. Go to `https://apply.opentech.fund/internet-freedom-fund/`
3. Scroll down to 'I acknowledge`
3. Click on `Read our mission, values, and principles.` or `Terms and Privacy policy.`

**Expected behavior**
Expect to be taken to the corresponding pages

**Priority**
- High 

**Affected roles**
- Applicants
- General public

**Desktop (please complete the following information):**
 - OS: MacOS v10.15.3 
 - Browser FireFox
 - Version 74

**Comment by frjo** [comment]
@fourthletter There is another issue for this, did you miss some form or is this just old information. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
I fixed the links.

1. In the wagtail admin page:
2. Go to Application Forms
3. I made edits to IFF-2020-01 and CIF-2020-01

**Comment by frjo** [comment]
@fourthletter Did you make the changes to the application forms linked to the funds as well so future rounds also have correct links?

If yes I think this issue can be closed.
