### ISSUE TITLE
Add the ability to "save application for later" or download application to work offline

### ISSUE THREAD

**Issue by georgiamoon** [OpenTechFund/hypha#1874]
**Is your feature request related to a problem? Please describe.**
During recent user interviews, users discussed challenges in working with the online application. One frequently mentioned challenge arises from the fact that I user may start on an application, realize that it is longer than they thought and would like to return to their in-progress application or download the application to work offline or in another collaborative editing tool with their team.

**Is your feature request related to an existing functionality? Please describe.**
This is related to the application form.

**Describe the solution you'd like**
There are a few ways this could be implemented:
1. Allow for a client side caching of the application so that the user has access to their data in the form without logging-in (Pros: People don't need to create accounts; Cons: Users might assuming that this behavior is introducing security risks, also many users disable javascript for security reasons)
2. Allow a way for users to "Save their progress & Continue" potentially prompting the user to login to an existing account or create an account on the site.
3. Allow users to download their work in-progress to another format, e.g. Markdown, Etherpad, Google Sheets, Word Documents.

**Additional context**
Regardless users are also interested in a downloadable version of the application to work in a separate document. I'll file this as a separate issue.

**Priority**
- Medium (slowing you down)

**Affected roles**
- Applicants

**Comment by danblah** [comment]
See #308 and #309 

My MVP pref
1. Immediately after they've inputted data to a field, an option to "Save & continue* is presented
2. Upon first save, the proposal is saved and a unique URL is created (no login required) to access the application
3. If they've inputted an email address, the URL is sent to their email as a reminder
4. Anyone with the URL is able to edit, delete, or submit the saved draft
5. After X days of inactivity (no views/edits) drafts are automatically deleted

Post mvp, auto saving, export/import.

cc @frjo and @saoun

**Comment by frjo** [comment]
@saoun Having a the system @danblah outlines in the [comment above](https://github.com/OpenTechFund/hypha/issues/1874#issuecomment-603191882) plus the system being built in https://github.com/OpenTechFund/hypha/issues/309 will be confusing I think, two ways to do the same thing.

I suggest we concentrate on https://github.com/OpenTechFund/hypha/issues/309 where users can save a draft and get an account on the system. Then later they can login and finish/submit the application.

Together with the script to copy the application form that is already in place I think we can close this issue.

Or we decide to scrap https://github.com/OpenTechFund/hypha/issues/309 and go for this issue instead.

**Comment by saoun** [comment]
@frjo agreed. we can close this and focus on #309 as it's essentially the same thing
