### ISSUE TITLE
Add the ability to download the application in a text format

### ISSUE THREAD

**Issue by georgiamoon** [OpenTechFund/hypha#1875]
**Is your feature request related to a problem? Please describe.**
During recent user interviews, users described their workflows which predominantly involved working in a collaborative document (e.g. Etherpad, Google Docs, or Markdown/Office document emailed around) with a team prior to submitting the application. It'd be great to support this workflow by providing the application content (e.g. questions) as a downloadable format so that users can work in their preferred application and then submit.

**Is your feature request related to an existing functionality? Please describe.**
This is related to the application.

**Describe the solution you'd like**
Just an idea, this would need some design work — There could be a "Download application template" prompt added to the beginning of the page and ideally at the base of the application as well.

**Additional context**
This is related to #1874.

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff
- Applicants
- Partners
- General public

**Comment by georgiamoon** [comment]
Interested related idea would be to allow users to apply by uploading the text based document and parsing the responses into the right sections of the application. I'm not putting this as a new issues, because I'm not sure if it's feasible at all.

**Comment by georgiamoon** [comment]
Some ideas here:
![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/7aba17e3-b877-45e0-a552-98adfbca63e9/Applicant_interviews_(4).jpg](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/7aba17e3-b877-45e0-a552-98adfbca63e9/Applicant_interviews_(4).jpg)

**Comment by georgiamoon** [comment]
Some ideas here:
![Applicant interviews (4)](https://user-images.githubusercontent.com/941210/77388903-d45ac900-6d67-11ea-8200-d5ade2be3a19.jpg)

**Comment by frjo** [comment]
On test I have now an implementation to test. A button at the bottom of every application form that copies all the questions to the clipboard.

**Comment by fourthletter** [comment]
This function works. We discussed moving the button on top and perhaps add text to explain this feature.

![image](https://user-images.githubusercontent.com/20019656/77651403-1e4bd680-6f43-11ea-92b1-a8cdc61ad17f.png)

**Comment by frjo** [comment]
Copy button are now on top on test with a title text that shows on hover.

**Comment by fourthletter** [comment]
Looks good to me. This button could go between the introduction paragraph and 'Basic Information' heading? 

![image](https://user-images.githubusercontent.com/20019656/77683492-d6db3f80-6f6e-11ea-9865-0e76eb909449.png)
