### ISSUE TITLE
Reduce and remove any tracking scripts

### ISSUE THREAD

**Issue by georgiamoon** [OpenTechFund/hypha#1877]
**Is your feature request related to a problem? Please describe.**
During recent user interviews, users raised questions about potential tracking scripts that might be collecting data on the site. The recommendation is to remove and/or reduce the use of scripts that might be collecting data on the application site.

**Is your feature request related to an existing functionality? Please describe.**
The application page.

**Describe the solution you'd like**
Clear disclosure around the use of any scripts and the removal of scripts to the extent possible.

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Applicants
- General public

**Comment by frjo** [comment]
Matomo is included via Cloudflare. I assume the recommended privacy settings are used so the data collected is anonymised as much as possible. 

I do not know anything else. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bumbleblue** [comment]
Adding context here from the interviews:
Right now the form requires javascript to work. A nice-to-have would be a javascript-independent form, or a form only requiring first-party javascripts (i.e. from opentech.fund). This is mainly for people who do not trust Cloudflare/Matomo with their data.
![image](https://user-images.githubusercontent.com/14316263/78036777-002f0d80-736b-11ea-9d56-04b178050944.png)

**Comment by frjo** [comment]
The reason user facing forms do not work without Javascript is spam. We have a crud but effective method that requires Javascript. The most common option is captchas but I think they are user unfriendly. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
The only tracking in use is Matomo and that I believe you want to have so closing this.
