### ISSUE TITLE
Allow multiple applicant users to edit an application

### ISSUE THREAD

**Issue by georgiamoon** [OpenTechFund/hypha#1878]
**Is your feature request related to a problem? Please describe.**
During recent user interviews, most users discussed working on their application collaboratively and the challenge of the system to only interact with them as an individual user, rather than having a team have access to the application content to help.

**Is your feature request related to an existing functionality? Please describe.**
The application page.

**Describe the solution you'd like**
- Allow applicants to add other applicants to an organization or an application that they can have edit rights to the application.
     - This assumes that you can save an in-progress application
     - Would require that the system can handle mutiple editors and/or async file lock out and conflict resolution

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Priority**
- Medium (slowing you down)

**Affected roles**
- Applicants
- Partners

**Comment by frjo** [comment]
Is this not the partner feature?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
related to #177

**Comment by georgiamoon** [comment]
@frjo I'm not sure what the Partner feature is, but #177 that @fourthletter tagged seems related/the same.

**Comment by saoun** [comment]
Related to https://github.com/OpenTechFund/hypha/issues/177 yes

Closing this here to consolidate with other.
