### ISSUE TITLE
When no payment requests are assigned to a OTF staff member the summary card should not show the view label

### ISSUE THREAD

**Issue by tmsndrs** [OpenTechFund/hypha#1884]
<img width="1391" alt="Screenshot 2020-03-24 at 13 40 55" src="https://user-images.githubusercontent.com/7290588/77431868-356cb600-6dd5-11ea-8102-d2935281d241.png">

When you click view it doesn't take you anywhere which is misleading for users.

**Comment by fourthletter** [comment]
Acceptance criteria was visible during test. Thank you!
