### ISSUE TITLE
Revise approved/invite to proposal email text and hyperlink 

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1891]
When a concept note is invited for a proposal two e-mails are sent out:

1. The determination itself with the determination message. This is sent for every determination. We want it to look like this:

~~~~
Dear Jane Doe,

Your application has been reviewed and the outcome is: Approved

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. …

Read the full determination here: http://apply.otf.test/apply/submissions/1233/determination/6543/

Here is the link to start creating your proposal: http://apply.otf.test/apply/submissions/1233/
If you have any questions, please submit them here: http://apply.otf.test/apply/submissions/1233/#communications

If you have any issues accessing the submission system or other general inquiries, please email us at hello@opentech.fund

Kind Regards,
The OTF Team
~~~~

2. The invite for proposal invite e-mail. We want it to look like this:

~~~~
Dear Jane Doe,

We’ve reviewed your Concept note and think it could be a good fit for OTF funding. We would like to invite you to submit a Proposal with more details about your project.

You can find more information about what we’d like to see in your Proposal here: https://guide.opentech.fund/general-funding-guidelines

The system will allow you to save a draft of your Proposal as you work on it. When you feel it is ready for our review, please click the “Submit” button and we’ll know to take a look at it. We’ll reply to you with feedback on your Proposal as quickly as possible.

Here is the link to start creating your proposal: http://apply.otf.test/apply/submissions/1234/
If you have any questions, please submit them here: http://apply.otf.test/apply/submissions/1234/#communications

If you have any issues accessing the submission system or other general inquiries, please email us at hello@opentech.fund

Kind Regards,
The OTF Team
~~~~

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff
- Applicants

**Comment by frjo** [comment]
When a concept note is invited for a proposal two e-mails are sent out:

1. The determination itself with the determination message. This is sent for every determination. It look like this.

~~~~
Dear Jane Doe,

Your application has been reviewed and the outcome is: Approved

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. …

Read the full determination here: http://apply.otf.test/apply/submissions/1233/determination/6543/

You can find more information here: http://apply.otf.test/apply/submissions/1233/
If you have any questions, please submit them here: http://apply.otf.test/apply/submissions/1233/#communications

If you have any issues accessing the submission system or other general inquiries, please email us at hello@opentech.fund

Kind Regards,
The OTF Team
~~~~


2. The invite for proposal invite e-mail. It look like this.

~~~~
Dear Jane Doe,

We’ve reviewed your Concept note and think it could be a good fit for OTF funding. We would like to invite you to submit a Proposal with more details about your project.

You can find more information about what we’d like to see in your Proposal here: https://guide.opentech.fund/general-funding-guidelines

The system will allow you to save a draft of your Proposal as you work on it. When you feel it is ready for our review, please click the “Submit” button and we’ll know to take a look at it. We’ll reply to you with feedback on your Proposal as quickly as possible.

You can find more information here: http://apply.otf.test/apply/submissions/1234/
If you have any questions, please submit them here: http://apply.otf.test/apply/submissions/1234/#communications

If you have any issues accessing the submission system or other general inquiries, please email us at hello@opentech.fund

Kind Regards,
The OTF Team
~~~~

**Comment by frjo** [comment]
@fourthletter The line "You can find more information about what we’d like to see in your Proposal here" is already present it seems.

**Comment by frjo** [comment]
@fourthletter The determination e-mail links to the concept note, not the new proposal. So saying "Here is the link to start creating your proposal" is incorrect.

**Comment by frjo** [comment]
I change the determination e-mail text to "Link to your application:" instead.

**Comment by frjo** [comment]
The PR is being deployed to test now, will be done in a few minuts and then you can test.

**Comment by fourthletter** [comment]
@frjo I edited the email content above. 

We are directing applicants directly to the submission: https://test-apply.opentech.fund/apply/submissions/38/

Could they start drafting their proposal using the above link? Or does the applicant need to be directed here:

![image](https://user-images.githubusercontent.com/20019656/77781952-d6a17980-702c-11ea-9cdd-109d217103cb.png)

**Comment by frjo** [comment]
@fourthletter A bit unclear if you want to send them to the dashboard or directly to the proposal? I think a direct link like now is better. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
@frjo 

In the email #2, the url after the sentence "You can find more information about what we’d like to see in your Proposal here:" is blank and does have the intended url to the guide.

**Comment by frjo** [comment]
The guide url setting was missing on test, I added it a little while ago. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
On live it had until today a small spelling error in the setting name. Fixed now. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
@frjo Thank you! 💥
