### ISSUE TITLE
Add the copy to clipboard to the bottom of the page, right justified in line with the apply botton

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1895]

**Comment by frjo** [comment]
We can add it there as well but I think having it on top is more useful. The users can interested in this feature want it before the fill time n the form. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saoun** [comment]
agree with @frjo. feels more useful at the top

**Comment by georgiamoon** [comment]
I would make a case for having the button in both places. Is there a reason why that wouldn't be possible?

Anyone agree/disagree with me? @ei8fdb @bumbleblue  ?
