### ISSUE TITLE
On OTF apply pages, why is the guide and clipboard right justified?

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1896]
is that on purpose? Seems like it should be left justified.

**Comment by frjo** [comment]
I thought it looked better, less messy. But probably a good idea to let a designer take a look. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by georgiamoon** [comment]
We are likely making suggestions about this as part of our re-working of the questions and the form. cc @bumbleblue @ei8fdb
