### ISSUE TITLE
Developer Onboarding - Torchbox on board Pete Andrew

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1902]
- [ ] Set up of dev environments 
- [ ] Todd has given a briefing on OTF project and infrastructure 
- [ ] Accounts access set up on dev and test

**Comment by frjo** [comment]
@abigail-hampson I have a working docker solution for local development, see PRs. Needs some documentation. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
