### ISSUE TITLE
Better Communicate Actions: Assign Reviewers 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/hypha#1904]
- [x] Assign reviewers button only shows if the submission does not have all reviewer roles assigned and is in internal review 
- [x] Assign reviewers button appears when it is in the external review stage 
- [x] Staff will always see 'update reviewers' in the reviews box, uses secondary button styling 

From #1851

**Comment by peteandrew** [comment]
@abigail-hampson this is ready for testing

**Comment by peteandrew** [comment]
@abigail-hampson sorry wrong one!

**Comment by peteandrew** [comment]
@abigail-hampson okay, this is now ready for testing

**Comment by abigail-hampson** [comment]
Looks good to me, over to OTF for testing - an example of where this can be tested is here - https://test-apply.opentech.fund/apply/submissions/37/

**Comment by fourthletter** [comment]
In this test application: https://test-apply.opentech.fund/apply/submissions/222/

I click on the 'Assign Reviewers' button and the Update Reviewers pop-up shows no reviewers have been assigned. This feature is misleading because the names of reviewers are not shown, the reality is that  one review has already been submitted to this application:

![image](https://user-images.githubusercontent.com/20019656/81022818-9eb40000-8e3c-11ea-9273-03f33a4d0863.png)

**Comment by peteandrew** [comment]
@fourthletter thanks for testing this. The 'Assign / Update Reviewers' pop-up is existing functionality. This ticket is concerned with adding the 'Assign Reviewers' primary action when the application has a specific state. Currently any user with the staff role is able to add a review to any application but there can be two users who are assigned as 'Primary Reviewer' or 'Secondary Reviewer'. The 'Assign Reviewers' primary action is shown when the application is in the 'Internal Review' phase and when either of the reviewer roles haven't yet been assigned.

**Comment by frjo** [comment]
@fourthletter Works well in my testing. But is it not in status "Screening" the "Assign reviewers" button should show?

When a submission reach "Internal review" reviewers are normally assigned already, is that not so?

P.S. There are action in place to move a submission from "Screening" to "Internal review" when two staff reviewers have been assigned.

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. Thank. you! 💥
