### ISSUE TITLE
Ability to delete application forms that are not associated to a round or a fund.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1910]
Very straight forward.

**Comment by fourthletter** [comment]
We can now delete a form within the Wagtail Admin or WebApp? How do we know it's not associated with a round or fund?

**Comment by fourthletter** [comment]
We can now delete a form within the Wagtail Admin or WebApp? How do we know it's not associated with a round or fund?

**Comment by Parbhat** [comment]
@fourthletter Delete button will only be displayed when an application form is not used by any Fund or Round. Forms which are used in a Fund will not have a delete button.

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. Thank you! 💥
