### ISSUE TITLE
Applicants can not save their proposal drafts 

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1914]
**Describe the bug**
Applicants that have submitted to IFF, ICFP, etc. are unable to save their proposal draft. **This problem could be tied to the mandatory or required address field embedded in the proposal.**

**To Reproduce**
1. Go to proposal as the applicant
2. Click on  'save draft'
3. The system does not respond and the draft does not save

**Expected behavior**
Applicant should be able to either save their draft or receive an error message to indicate the issue.

**Priority**
- Medium (slowing you down)

**Affected roles**
- Applicants

**Comment by frjo** [comment]
@fourthletter But if they fill in all required fields, then they can save, correct?
