### ISSUE TITLE
New activity notification banner doesn't go away unless a hard refresh happens

### ISSUE THREAD

**Issue by harumhelmy** [OpenTechFund/hypha#1924]
**Describe the bug**

On my local hypha build, the message banner that appears at the top of a page after submitting a new comment/adding a review/basically any activity doesn't go away even when you click the "Ok" button on the banner. It only goes away if you refresh the page. Does this happen on anyone else's build? (I checked the sandbox (test.opentech.fund) by submitting a dummy project and the new activity banner does not show up at all on that site.)

**To Reproduce**

1. Go to any submission detail page. I use the sandbox db to populate my local build, so I go to http://apply.hypha.test/apply/submissions/2/ 
2. Perform any activity, for example: adding a new message/comment on the submission under the Communications tab
3. After you submit your new message, the page refreshes and a new message notification banner appears at the top of the page. The banner includes an "Ok" button that doesn't do anything 
4. The banner doesn't go away

**Expected behavior**

The "Ok" button should make the banner disappear. Looking at the JS

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

(I reproduced this bug when using the app as the different below roles on my local build) 

- Staff
- Applicants
- Reviewers
- Partners

**Screenshots**

![hypha-message-bug-repro](https://user-images.githubusercontent.com/13320420/79007066-657fbd00-7b28-11ea-9e30-3f3bf6bc6359.gif)

**Desktop (please complete the following information):**

 - macOS Catalina 
 - Chrome

**Comment by frjo** [comment]
I can confirm this bug. Want to tackle it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
This was due to the javascript being loaded to early, fixed when moving the main.js to the bottom.
