### ISSUE TITLE
Refactor Dashbord views to remove redundancy and make easier to understand

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1936]

**Comment by frjo** [comment]
See discussion in https://github.com/OpenTechFund/hypha/pull/1928.

**Comment by Parbhat** [comment]
The dashboard view is already [using](https://github.com/OpenTechFund/hypha/blob/d7181b723de077d311477b58763f7b5d4bdfa8ad/hypha/apply/dashboard/views.py#L358) ViewDispatcher. It is about abstracting duplicate code from views in a base class. And inherit in main views. Some code in [get](https://github.com/OpenTechFund/hypha/blob/d7181b723de077d311477b58763f7b5d4bdfa8ad/hypha/apply/dashboard/views.py#L134) methods can also be in [get_context_data](https://github.com/OpenTechFund/hypha/blob/d7181b723de077d311477b58763f7b5d4bdfa8ad/hypha/apply/dashboard/views.py#L210) method.
