### ISSUE TITLE
Add the ability for users to add multiple single text fields in response to a question, e.g. multiple URLs

### ISSUE THREAD

**Issue by georgiamoon** [OpenTechFund/hypha#1954]
**Is your feature request related to a problem? Please describe.**

N/A

**Is your feature request related to an existing functionality? Please describe.**

We would like to have a question type that allows a user to create a list of URLs. This would be a new question type in the field builder for hypha.

**Describe the solution you'd like**

MVP: A field type that is a single text line and does URL validation
Ideal: A field that allows a user to add multiple lines of URLs that are validated

Sketch:
<img width="370" alt="Screen Shot 2020-04-28 at 9 52 26 AM" src="https://user-images.githubusercontent.com/941210/80495507-039bc180-8936-11ea-9b91-40e1bbb278b8.png">

**Describe alternatives you've considered**

This is an initial idea, so I welcome feedback and technical needs/constraints to consider.

**Additional context**

This is an idea coming out of the application question user feedback process with OTF.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners
- Developers
- General public

**Ideal deadline**

Q2/Q3 2020

**Comment by Parbhat** [comment]
@georgiamoon The form builder has a field type that is a single text line and does URL validation. It can be created by selecting `Text Field (Single Line)` and choosing `URL` in the format option. List of URLs is not supported currently. Looks like MVP for this issue is already present.

**Comment by frjo** [comment]
@Parbhat Thanks for reminding me of that functionality. I have seen it but managed to forget it.

**Comment by georgiamoon** [comment]
The field allows the staff to add that option is that correct? 

What we were envisioning is a way for applicants to be able to add multiple URLs, e.g. the form might start with 2-3 fields, and an end user could add an additional one if they need it. Does that make sense? I more dynamic entry, but structured?

**Comment by frjo** [comment]
@georgiamoon This is the "Text field (single line)" that you can add to application forms. Allowing the form to request a url from the applicant.

The missing part is the ability to ask for more than one url per field.

**Comment by georgiamoon** [comment]
I updated the subject line to be clearer hopefully!

**Comment by Parbhat** [comment]
Thanks, got the requirements for the feature.

**Comment by ei8fdb** [comment]
@Parbhat @frjo I've picked up this ticket (and #1948). 

Is there anything design related you need?

**Comment by Parbhat** [comment]
Good, not sure some design work require currently. But we will need to first come up with an implementation plan.

**Comment by ei8fdb** [comment]
@Parbhat OK let me know if you need.

**Comment by fourthletter** [comment]
To add multiple single text fields in response to a question, go to a form within WagTail admin and select **Text field (single line)(multiple inputs**
![image](https://user-images.githubusercontent.com/20019656/86351295-06ff4200-bc32-11ea-8a57-6a42ab9f6ee1.png)

This text field renders renders as this when live. The 'Add new item' button is function:

![Screenshot 2020-07-02 at 7 00 19 AM](https://user-images.githubusercontent.com/20019656/86351505-58a7cc80-bc32-11ea-9d74-51f2fd033384.png)
