### ISSUE TITLE
Improve the content output of the "copy questions to clipboard" function on fund pages

### ISSUE THREAD

**Issue by ei8fdb** [OpenTechFund/hypha#1959]
**Is your feature request related to a problem? Please describe.**

The content output of "copy questions to clipboard" button on the IFF application page contains 1) unhelpful text, and 2) does not include the help guide links [IFF application page](https://apply.opentech.fund/internet-freedom-fund/).

## Context
This affects the current IFF application form. When the form is redesigned, the content of the copy to clipboard function will need to be modified.

### User behaviour
From research we know IFF applicants write their project proposal document collaboratively: in Google Docs, Etherpads, etc. They only spend time in the application form to copy and paste the answers into the form.

Therefore they need to see all the application form content.

### Problem
When a user hits the "copy questions to clipboard" the section headers, questions, and labels are copied, but the "See help guide for more information" content and the associated hyperlinks are not copied.
 
**Is your feature request related to an existing functionality? Please describe.**
It is part of the  "copy questions to clipboard" function on the IFF application page.

A clear and concise description of what or where the existing page or function is. Include URLs.
It is on the [IFF application page](https://apply.opentech.fund/internet-freedom-fund/).

**Describe the solution you'd like**

0. User visits the page where the "copy questions to clipboard" button is displayed 
1. a user presses the "copy questions to clipboard" button
2. the section headers, questions, and labels, "See help guide for more information" content and the associated hyperlinks are copied to clipboard
3. When the user pastes them into their document the content is formatted as simple markdown.

I've put together [a proposed output file](https://github.com/ei8fdb/otf-iff-application-hypha/blob/master/copy-to-clipboard-proposed-output.md) which would satisfy users needs.  If you do a diff against [the current clipboard output](https://github.com/ei8fdb/otf-iff-application-hypha/blob/master/copy-to-clipboard-current-output.md) you'll see what I've included.

The main differences are inclusion of links, and content that wasn't included currently, removal of some text (mainly numbers).

**Describe alternatives you've considered**

The only alternatives are the applicant must go back to the application form an copy them one-by-one, or do without the links - this is not ideal, as they can miss vital explanatory information that helps them answer the question.

**Additional context**

This is a screenshot of the function in question:
![Screenshot of the Copy questions to clipboard button](https://user-images.githubusercontent.com/1899506/80512353-4630be80-8975-11ea-9f43-0128e6940a11.png)

**Priority**
- Medium (slowing you down)

**Affected roles**
Fund applicants

**Ideal deadline**

**Comment by frjo** [comment]
Guide links should be copied, missed that one when I built this feature. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ei8fdb** [comment]
@frjo Super. The question "hint" texts must be included too - e.g. for question "What are hoped for goals or longer term effects of the project?" the hint text:

> We want to know how you think the world could be, what larger purpose this project is a part of, and/or the bigger target you are aiming for? (max 800-1000 words)

must be included too.

**Comment by frjo** [comment]
@ei8fdb @georgiamoon This is now on the test site so you can test it.

I believe I added all the things you noticed. Thanks for very clear description and examples!

I also added that checkbox labels for checked boxes gets an asterix after its name. Maybe not optimal choice since the same asterix is used to indicate required fields, ideas?

**Comment by ei8fdb** [comment]
> I also added that checkbox labels for checked boxes gets an asterix after its name. 

From our discussion today we'll use your example:

An application form has a category question “Objectives. 

If the user had not checked any alternatives it would look like this:

`### Objectives

Deploying technology
Software or hardware development
Testing
Research
Technology development
Training'

and the user had checked “Research” and “Training” it would look like this.

'### Objectives

Deploying technology
Software or hardware development
Testing
Research*
Technology development
Training*'

@frjo thinking about this this afternoon:

Instead of using "*" to signify the user has selected the option use the word: (selected)

My reasoning being - "selected" makes it clearer what's happened, the user selected this.

Using a character like * would need explanation 


e.g.
If the user has *not* answered the question, the options would look like this:

`### Objectives

Deploying technology
Software or hardware development
Testing
Research*
Technology development
Training*'

If the user has answered the question, and selects research and training options would look like this:

`### Objectives

Deploying technology
Software or hardware development
Testing
Research(selected)
Technology development
Training(selected)'

@georgiamoon @frjo  thoughts?

**Comment by frjo** [comment]
Made that change in the PR now and deployed to test.
