### ISSUE TITLE
Add a batch delete function to the all submissions view

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#1964]
Pretty straight forward. Make sure there's a confirmation.

**Comment by frjo** [comment]
This feels dangerous.

**Comment by Parbhat** [comment]
All sumissions view is `/apply/submissions/all/`

**Comment by frjo** [comment]
@sks444 PR https://github.com/OpenTechFund/hypha/pull/2088 adds this functionality very nicely.

But should really all staff have access to this? @saoun @fourthletter

**Comment by fourthletter** [comment]
@frjo This feature should probably be reserved for Admin. I think the rationale was last year when we received a hundred of spam submissions.
