### ISSUE TITLE
Delete button for Fund in wagtail admin should not show if there are related rounds

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1971]
Similar solution to https://github.com/OpenTechFund/hypha/pull/1968 I believe.

**Comment by frjo** [comment]
@vaibhavmule In https://github.com/OpenTechFund/hypha/pull/1968 you made sure that only unused application forms gets the delete button. Can you do a similar thing for Funds? If they have related rounds the delete button should not show.

Trying to use it now results in an error. "Cannot delete some instances of model 'Page' because they are referenced through a protected foreign key:…"

**Comment by Parbhat** [comment]
The fund model is Wagtail's Page model and very different from `ApplicationForm` model. So, needs a different approach. ProtectedError currently does not get caught in Page models. More details in   https://github.com/wagtail/wagtail/issues/1602. Implemented a workaround in PR #1976.
