### ISSUE TITLE
Add 'Request More Information' option to 'Read for Determination' status

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#1983]
[ ] Go to application: https://test-apply.opentech.fund/apply/submissions/223/
[ ] In the 'Read for Determination' status, please enable 'Request More Information' option. Users is currently only able to select 'Dismiss' or "Accept' at this stage, limiting available options.

**Comment by saoun** [comment]
@fourthletter i dont see the error. I'm able to select "ready for determination" on this application. 

Is this still coming up for you?
