### ISSUE TITLE
Pagination of the application form

### ISSUE THREAD

**Issue by bumbleblue** [OpenTechFund/hypha#1991]
**Is your feature request related to a problem? Please describe.**

Currently all forms are implemented on a single page. It would benefit applicants to focus on individual sections.

**Describe the solution you'd like**

Pagination; navigation between different sections (previous, next) as well as an indicator for progress (progress bar).

**Priority**

- Low priority

**Affected roles**

- Applicants

**Ideal deadline**

By June

**Comment by frjo** [comment]
Duplicate of https://github.com/OpenTechFund/hypha/issues/1961 I think.

**Comment by bumbleblue** [comment]
Ah yes, my bad for not checking!

**Comment by frjo** [comment]
No problem, more important to get vital issue in to the system.
