### ISSUE TITLE
Clean db value data and use db function for result calculation

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#1999]
Using db functions for calculations all make this feature far more performant, at least around 5x.

For this to work the db needs to have clean values in the db. The linked PR has a script to clean old values.

An issue is that file the correct number fined will make sure only positive numbers are submitted from now on it does allow commas and periods as thousand separators etc.

How can we handle this?

**Comment by frjo** [comment]
@Parbhat The db functions does not seem to work with numbers like "100.000.00" or "100.000" etc. it wants plain "100000".

Any suggestion for how to handle this?

A way to clean numbers on the fly before calculation with db function?

Add field validation that force applicants to restrain from using comma and period?

**Comment by Parbhat** [comment]
@frjo The error happens not in the db aggregation function like Sum but in the annotate method. We need to change `output_field` in the Cast function from `IntegerField` to `FloatField`. As if a value in the db is `"500.00" ` (a string), it can not be cast to Integer but can be to FloatField. Tested locally, changing this line fixes the issue.

https://github.com/OpenTechFund/hypha/blob/1975e7d7de47ef731ebe7bcdbb0ece50e63d16cb/hypha/apply/funds/views.py#L1148 

It seems better to not change anything in client validation for number input.

**Comment by frjo** [comment]
@Parbhat Thanks, will test that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
