### ISSUE TITLE
Remove automated notifications about new proposals ready for AC review in IFF & CIF

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#2008]
As a user (AC reviewer) I do not want to receive automated notification emails regarding new proposals because I am receiving other more substantive emails directly from OTF team members.

For proposals in IFF and CIF in the state "Ready for AC Review" will not send an auto generated email notification to all AC reviewers assigned to this proposal.

**Comment by frjo** [comment]
@fourthletter So you want a setting on each Lab and Fund to specify if notifications to reviewers should be sent or not?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
@frjo is this approach feasible? If not, we could remove it for all funds and labs. Majority of staff are saying they do NOT use and rely on the automated proposal notification.

**Comment by frjo** [comment]
Implemented a new setting "SEND_READY_FOR_REVIEW". On Test I have now set it to "false".

This feels wrong somehow, moving functionality out of the system to a manual process. But with this setting it's optional and defaults to sending review notifications as before.

**Comment by frjo** [comment]
[hypha-schema.pdf](https://github.com/OpenTechFund/hypha/files/4675823/hypha-schema.pdf)

**Comment by fourthletter** [comment]
This is awesome! Thank you.
