### ISSUE TITLE
Regarding django-extensions and more-itertools

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2015]
* django-extensions: Is this not a development extension or is it used for production as well somewhere? If not we could move it to "requirements-dev.txt" and load it only if DEBUG is true.
* more-itertools: This is used only once in a test function from what I can see. Easy to rewrite and remove? See https://github.com/OpenTechFund/hypha/blob/master/hypha/apply/projects/tests/test_files.py

**Comment by Parbhat** [comment]
`django-extensions`: Yeah, it is used in the development and found only one use in vagrant [file](https://github.com/OpenTechFund/hypha/blob/79b19da6020f3d59b42656168c12da53e1f95739/vagrant/provision.sh#L52).
`more-itertools`: Looks like we can continue to have it as provide a lot of [helper](https://github.com/more-itertools/more-itertools#more-itertools) functions.
