### ISSUE TITLE
On the round detailed/list view (the one with the notes), provide the same side bar with all the same options under the the "Status" tab as is in the submission's own page

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#2030]
Why don't' we already do this? I want to stay on this page so much more but I can't do anything but take notes on an application.

**Comment by frjo** [comment]
We need a React developer to implement that. Some work I guess.  

If this feature is going to stick around it needs some work. Updating React at least. 

I would prefer to rebuild it in something more lightweight. The app is now on n excess of 1 MB now! Maybe a good react developer can bring that down as well. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Parbhat** [comment]
@frjo Looks like we have created all required options in React app similar to a Submission detail page's sidebar under status. We may close this issue and create new issues for any other options required.
