### ISSUE TITLE
Update React packages to latest version

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2036]
Update all the react packages in package.json to latest versions possible.

**Comment by frjo** [comment]
@Parbhat If you have people that know React but love something simpler and cleaner like e.g. https://svelte.dev/ I would be interested in discussing time needed to switch.

If your people know and love react then we just stay with that.

**Comment by Parbhat** [comment]
@frjo Sticking with React will be good as a good amount of work is already done with it in the project. React is heavy and has a decent learning curve compared to Vue/Svelte. Svelte looks good and Vue.js is also commonly used in Django projects as can be used like JQuery without much tooling and a lot simpler. But in complex features, there will not be much difference. So, we will probably need a React specialist.

Just to confirm, we are using React currently in 2 pages: Submissions by Round (ex `/apply/rounds/18/?submission=13`) and Submissions by Status (`/apply/submissions/internal-review/?submission=4`).

**Comment by frjo** [comment]
@Parbhat Yes, that is the two sections that is powered by React.
