### ISSUE TITLE
Slim down the React app if possible

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2038]
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  submissionsByRound-af367a97275ff7253905.js (931 KiB)
  submissionsByStatus-af367a97275ff7253905.js (931 KiB)

**Comment by frjo** [comment]
@Parbhat  We no longer need to support IE 11. Cloudflare takes care of minifying JS/CSS.

This may make it possible to remove or at least slim down the babel and polyfill parts.

Vanilla ES6 JavaScript works as far as I know well in all modern browsers so no longer any need to convert it.

**Comment by vimal1083** [comment]
Hi @frjo,
Recently joined the team, Hope you're doing good.

We use Babel and polyfill to transpile our source code, the converted source will not have much difference in size. also source code of   Babel and polyfill will not go into the build file, so removing these packages will not help us to reduce the build size.

We have two entry points submissionsByRound and submissionsByStatus, both has the same  node modules we have installed. which means  submissionsByRound has `react-rte` and submissionsByStatus also has the same. If we separate out the common modules browser doesn't have to download `react-rte` twice.
<img width="1679" alt="Screen Shot 2020-08-17 at 23 25 04" src="https://user-images.githubusercontent.com/8245654/90522022-db57fd00-e188-11ea-81e5-2c32e9e2b5ea.png">

I have used webpack's splitchunksplugin to split out common modules 

`Entrypoints:
  submissionsByRound (954 KiB)
      vendor~ff0192b0.91c2e04d7b7b7d277b35.chunk.js -> 183 KB
      vendor~28c49287.06e49f6ea427461fbe57.chunk.js -> 618 KB
      submissionsByRound~submissionsByStatus~493df0b3.a394ef9afffd5519c6ac.chunk.js --> 222 KB
      submissionsByRound~d0ae3f07-d10b22e5b7edd76c96b6.js -> 3.9 KB
  submissionsByStatus (953 KiB)
      vendor~ff0192b0.91c2e04d7b7b7d277b35.chunk.js -> 183 KB
      vendor~28c49287.06e49f6ea427461fbe57.chunk.js -> 618 KB
      submissionsByRound~submissionsByStatus~493df0b3.a394ef9afffd5519c6ac.chunk.js --> 222 KB
      submissionsByStatus~d0ae3f07-d10b22e5b7edd76c96b6.js` -> 17 KB

Here we have all our `node_modules` in to `vendor` chunks. So our dependencies will be downloaded once. our actual application code is around 240KB.


But still we get that yellow colored warning message saying your entry point size is greater than 250 KB, to get rid of that we should do gzip compression on build file. As you have mentioned compression is happening in CDN we can pretty much ignore this warning.

**Comment by frjo** [comment]
@vimal1083 Welcome to the project! Nice start! Even if the Babel and polyfill do not add to the size they do add complexity. Since we only support modern browsers can we not skip he transpile?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vimal1083** [comment]
Each browser has their own javascript engine with a different level of ES6 support, browser's javascript engine's release cycle does not go in hand with Ecmascript. If we don't transpile  our code we may get different bugs in  browsers.

For example 

```
import a from 'a' // this line worked in chrome but not in firefox
```

for firefox it should be 
```
import a from 'a.js'
```
I have seen this issue some time back, now it may be resolved. Similarly we will get small weird errors. That is why I recommend to transpile.

**Comment by frjo** [comment]
@vimal1083 Then we leave it in, thanks for the explanation.

I'm not strong when it comes to JavaScript so therefor strive to keep that part as simple and clean as possible.

**Comment by Parbhat** [comment]
@vimal1083 Can we close the issue?
