### ISSUE TITLE
Remove default hard coded "notify" channel from funds. 

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2040]
All funds will then need to explicitly set the Slack channel.

**Comment by frjo** [comment]
@saoun This sounds ok to you. I think this makes more sense not that more organisations are using Hypha.

**Comment by saoun** [comment]
Sounds good.

Flagging for @fourthletter

**Comment by frjo** [comment]
If one or more custom Slack channel(s) is set on a Fund that will be used. If nothin is set the default SLACK_DESTINATION_ROOM is used instead.

Today they are merged and a notification is sent to all the channels.

**Comment by fourthletter** [comment]
I reviewed, thank you!
