### ISSUE TITLE
For review forms and the score field, ability to exclude the text field (only include the rating/scoring field) and/or ability to have it collapsed by default. 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#2050]

**Comment by ankitjavalkar** [comment]
@frjo I noticed that there is already a ScoreFieldWithoutTextBlock that is available - https://github.com/OpenTechFund/hypha/blob/master/hypha/apply/review/blocks.py#L57Does this satisfy the basic requirement for the issue (ability to exclude the text field (only include the rating/scoring field)?

**Comment by frjo** [comment]
@ankitjavalkar You are correct, will close this issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
