### ISSUE TITLE
For review forms and the score field when marked required, do not make entering text into the text box required but do make submitting a score required. 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#2053]

**Comment by danblah** [comment]
Alternatively, just create a score field w/o a text box @frjo

**Comment by sks444** [comment]
@frjo wanted to confirm, if it is okay to move forward with the implementation of new `ScoreFieldWithoutTextBlock`.

**Comment by frjo** [comment]
@sks444 Yes, that sounds good.
