### ISSUE TITLE
Setting for Salesforce Integration

### ISSUE THREAD

**Issue by maxpearl** [OpenTechFund/hypha#2054]
Suggestion: Add a setting under Wagtail admin: /admin/settings/utils/systemmessagessettings/2/ to activate salesforce integration. This would requires modifying the class SystemMessagesSettings(BaseSetting) in hypha/public/utils/models.py, giving something like this:

![Screenshot_2020-06-16_12-16-46](https://user-images.githubusercontent.com/144151/84818429-55260b80-afcb-11ea-89fe-afb5886cd40b.png)

**Comment by maxpearl** [comment]
[Here's a potential pull request](https://github.com/maxpearl/hypha/commit/bac7cb9543845683a0f55715409527f08ca833ab) but I'd like to wait until we have a new branch for this work.

**Comment by frjo** [comment]
@maxpearl I think I would prefer to add this as an environment variable. OR is it something an site admin will need to turn on/off from time to time?

The API keys will need to be environment variables in any case and a developer will need set it all up.

Maybe we could use the existens of an Salesforce API be the toggle itself? If the key(s) is preset the integration is active? Or if you see a usecase for a separate toggle we add that of course.

**Comment by maxpearl** [comment]
I'm adding a combination of an environment variable and an additional settings file, as there are a lot of settings to include.
