### ISSUE TITLE
On the react interface, add "Determination" and "Review" buttons

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#2068]
* Upon click
* If draft exists, load the draft, if no draft, create a draft
* Collapse the leftmost screening sidebarS
* Shift the proposal page left and replace status/notes with a determination/review form
* Autosave draft as things are inputted
* Have a X/Close icon in the top right of that pane
* Upon click of X/Close, resize/go back to all default view

**Comment by sks444** [comment]
@frjo seems like this requires respective APIs to create/edit/retrieve reviews and determinations. Given that the reviews and determinations apps are now kind of similar, apis implementation would also be somewhat similar. So we can focus first on review APIs and then determination APIs:

- First problem that comes to mind is, given that our fields are dynamic how will frontend know what fields to show in the form:
  - To solve this we can have an endpoint(`submissions/id/reviews/fields`) to list details of all the fields available in the review form of a submission. Which frontend can use to construct the form.
  - We can get the fields by using [get_fields_for_stages](https://github.com/OpenTechFund/hypha/blob/6079f5b2d9a734d8bcd38302f3f577ecffb00bcc/hypha/apply/review/views.py#L52) for a submission.

- Second, we also need to have a serializer defined to validate the submitted data from frontend:
   - This requires us to create serializer fields dynamically from streamfield blocks, we can do this similar to how we [create form fields from streamfield blocks](https://github.com/OpenTechFund/hypha/blob/6079f5b2d9a734d8bcd38302f3f577ecffb00bcc/hypha/apply/stream_forms/models.py#L49).

- Once the data is validated from serializer we can do all the processing that we do while handling the form data and save the Review object.

**Comment by frjo** [comment]
@sks444 Implementing this first for Reviews sounds good. Will be easy to replicate that for Determinations later.

**Comment by sks444** [comment]
Making a TODO of things done and of things needs to be done to help the development process:
- [ ]  Get a dynamic serializer working with only a few [stream field blocks](https://github.com/OpenTechFund/hypha/blob/master/hypha/apply/stream_forms/blocks.py)

- [ ]  `/submissions/id/reviews/fields` Develop an api to list available review fields according to a submission stage, which frontend would use to submit a review.

- [ ] `/submissions/id/reviews/` Develop an api to create reviews, validate the post data through dynamic serializer and save the review object. Should also return the serialized review object in the response which should be same as the response of `/submissions/id/reviews/id`.

- [ ]  `/submissions/id/reviews/id` Develop an api to get the details of a review, response should also [include opinions ](https://github.com/OpenTechFund/hypha/blob/5ce2cea685ad1cc5485be349a3d4f4f1c95b801a/hypha/apply/review/templates/review/review_detail.html#L10)on the review, and fields like `recommendation`, `score`, `visibility` along with [recommendation comments](https://github.com/OpenTechFund/hypha/blob/5ce2cea685ad1cc5485be349a3d4f4f1c95b801a/hypha/apply/review/templates/review/review_detail.html#L54) and [other submitted answers](https://github.com/OpenTechFund/hypha/blob/5ce2cea685ad1cc5485be349a3d4f4f1c95b801a/hypha/apply/review/templates/review/review_detail.html#L56). 

- [ ] `/submissions/id/reviews/` Develop an api list all the reviews on a submission. Cunstruct the serializer based on the [context data](https://github.com/OpenTechFund/hypha/blob/5ce2cea685ad1cc5485be349a3d4f4f1c95b801a/hypha/apply/review/views.py#L350) and only include the fields which are included there. 

- [ ] `/submissions/id/reviews/id` Develop an api to update/edit a review, this should fairly be similar to create review api.

- [ ] `/submissions/id/reviews/id/` Develop an api to delete a review.

- [ ] `/submissions/id/reviews/id/opinions` Develop an api to create review opinions on a review, include it in the SubmissionReviewViewSet with action, no need to create a separate ViewSet. I think review opinion options could be hardcoded in frontend, as it is only `Agree` and `Disagree`.

- [ ] Check if correct users has right permissions on all the apis. May need to develop permission classes for write and read review and include it in the view.

- [ ] Make support of other stream field blocks to dynamic serializer.

- [ ] Make support for custom field serialization to dynamic serializer. I.e. `ScoredAnswerField`

- [ ] Structure code, create a review directory, where review views, utils and mixin could be included.

- [ ]  Write documentations where needed.

- [ ]  Get the react developer to start implementing the review apis in frontend. And make improvements to the apis according the frontend requirement.

- [ ] Write unit tests for all the apis for which tests are possible.

- [ ] Start working on the determination apis.

**Comment by sks444** [comment]
Some Updates:

> Create a mapping of form fields to serializer fields. A reference could be taken from how rest framework maps model field to serializer field. Use this mapping to get serializer field class from form field class from stream field blocks.

Seems like mapping is not necessary for now as the form fields we use has respective fields with same name in Serializer. We can implement this later maybe while implementing determination apis if needed.

> /submissions/id/reviews/ Develop an api list all the reviews on a submission. Cunstruct the serializer based on the context data and only include the fields which are included there.

List view of reviews with django forms is pretty good. So I have commented out the apis for this for now. Maybe we can do this later once the initial feature of review has been implemented in frontend.

> Make support for custom field serialization to dynamic serializer. I.e. ScoredAnswerField

- [ ] This is still in TODO. `ScoredAnswerField` accepts inputs in form of list, so I am using ListSerializer for now. But the validation of the values in the list has to be done. 

TODOs:

- [ ]  Allow `create` and `edit` apis to be saved as draft. 

Along with above two only the testing of the apis is remaining.

All the work has been pushed at https://github.com/OpenTechFund/hypha/pull/2101

[Here is a link](https://www.getpostman.com/collections/a6d2717f1cb63f515072) to postman collection of the apis which can be imported for testing purposes. We can not use the automatic generated doc for post apis as the tool doesn't yet support dynamic serializer.

**Comment by fourthletter** [comment]
I was able to create and submit a review within the React app.

**Comment by sks444** [comment]
@frjo, next, I have been working on the determination apis.

We are planning to not support the old determination django forms in the api and react interface. Basically we will only show Add determination button in React app for funds which have set new streamfield forms. And not show for funds which uses old determination forms.

Since they are being deprecated, it wouldn't be worth the effort of handling two flows in the apis. Here are the steps that we need to do for the support:
- Check if streamfield form is not attached render api fields for old django forms.
- Handling the two flows of and saving and retrieving the submitted data: as earlier we used to save it in [data](https://github.com/OpenTechFund/hypha/blob/96c3fc2e7586deceb72b9da5610c9b70aa449478/hypha/apply/determinations/models.py#L102) field instead of [form_data](https://github.com/OpenTechFund/hypha/blob/96c3fc2e7586deceb72b9da5610c9b70aa449478/hypha/apply/determinations/models.py#L105).
- Handling the [grouping of fields ](https://github.com/OpenTechFund/hypha/blob/bf8e9f3f10245dcea71b2c8ff1d8a7bc6efacede/hypha/apply/determinations/forms.py#L173)for the detail page.

There are other benefits of not having this in our code like cleanliness and consistency with our review api code.

Let us know your opinion on this.

**Comment by frjo** [comment]
@sks444 Definitely the right call to not support the old determinations forms in the API/React app.

**Comment by sks444** [comment]
Open funds on test site doesn't have the stream field determination form attached.

`Add determination` feature in react is only available on submissions for funds which have the determination form attached. I have added new fund https://test-apply.opentech.fund/add-determination-test-react-app/ which can be used for testing purposes.
