### ISSUE TITLE
On the application listings, on the same line as filters and search bar, present pagination options 25 (default), 50, and 100 per page and show how many of total applications is presented, eg "1-25 of 100".

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#2075]

**Comment by danblah** [comment]
Make sure this works for any filters as well.

**Comment by frjo** [comment]
@Parbhat How mush work would this be?

**Comment by Parbhat** [comment]
@frjo Looks like we need the functionality at Submission List view `/apply/submissions/all/`. There is already pagination with default per page size of 25. The requirement is to show page size dropdown with choices 25, 50 and 100 at the top (same line as filters and search bar). Backend work for pagination is already there (`/apply/submissions/all/?status=screening&query=&per_page=1&page=1`) so we will need to work on Frontend updates.

**Comment by frjo** [comment]
@Parbhat "&per_page=1", will see if I not can fix that, thanks.

**Comment by Parbhat** [comment]
Not sure I got last comment correctly. But we do not need to fix &per_page=1, as it is feature which allows to paginate with default value of 25. I manually queried 1 to show we can also set 50 or 100 for pagination.
