### ISSUE TITLE
Error Message When Sending Determination

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#2114]
**Describe the bug**

An error occurs when user sends out determination. This is occurring across all funds, and on the live site as well. Here is the test url https://test-apply.opentech.fund/apply/submissions/27/ 

![image](https://user-images.githubusercontent.com/20019656/91151503-0a58fc00-e6be-11ea-88c0-7d086e502e77.png)

**To Reproduce**

1. Go to a submission
2. Click on add determination
3. Sends determination
4. See error appears after the determination has been sent

**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Staff
- Applicants

**Comment by frjo** [comment]
@fourthletter  Tested a bit locally and it seems to work as it should. The test submission you linked to have a determination and is dismissed. Did you get it to work later on?
