### ISSUE TITLE
Add possibility to open any selection of submissions in the React app

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2135]
Add the possibility to open any selection of submissions in "/apply/submissions/all/" in the React app.

![reactapp](https://user-images.githubusercontent.com/191392/94155092-d9b3e000-fe7e-11ea-807f-4d3c247db6f1.png)

**Comment by Parbhat** [comment]
@frjo Not sure if I got the requirements correctly. Do we need to show only the submissions in React app which are visible in the table after filtering?

**Comment by frjo** [comment]
@Parbhat Yes, that was my idea.

As of now you can open the React app per round (/apply/rounds/1126/) or per status (/apply/submissions/more-information/). I believe it would be useful to open with any selection you make in "/apply/submissions/all/".

What do you think? Easier/better to add the filtering directly in the React app and allow it to be open with all submission?

**Comment by Parbhat** [comment]
@frjo Thanks for the details. The react app currently does not have an entry point from `"/apply/submissions/all/"`. We will look into it closely which would be the best option.

**Comment by Parbhat** [comment]
@vimal1083 Let's first create an entry from All submissions page  (`"/apply/submissions/all/"`) to React app. Then create a plan for Filtering options. Looks like it would be better to have filter options in React app itself. Filtering can be implemented in separate PR along with related issue #2031. The current entry points have left sidebar with filtering already performed according to the page.

1. React app entry from Status (`/apply/submissions/internal-review/`): Left sidebar is based on Round and choosing the Round in filter scrolls to the submissions in that Round.
2. React app entry from Round (`/apply/rounds/877/`): Left sidebar is based on status and submissions are grouped by status.

Entrypoint from all submissions page, we can show sidebar based on Round only or combination with status. We also do not show current status in React app in details of submissions/right sidebar so need to look into that as well. @ei8fdb Can you look into this and what options would be good if entry point into React app is from All submissions page?
