### ISSUE TITLE
3 panel group-listing dropdown filter does not apply

### ISSUE THREAD

**Issue by ei8fdb** [OpenTechFund/hypha#2147]
In the 3-panel review interface, the dropdown in left-hand side does not apply filter. 

**Describe the bug**

**To Reproduce**

1. Go to [test instance](https://test-apply.opentech.fund/apply/rounds/824/?submission=81)
2. Click on 'External' in dropdown
3. Select 'Accepted'
4. Instead of seeing just Accepted applications, you see ALL applications - Accepted, External Review, etc.
**Expected behavior**

When user clicks on Accepted, only applications that have that status should appear.

**Priority**

- Medium (causes annoyance, but also fundamental usability issue)

**Affected roles**

- Staff
- Reviewers
- ?

**Screenshots**
![image](https://user-images.githubusercontent.com/1899506/96470317-124c9c80-1226-11eb-9f61-435a53d1f427.png)

![image](https://user-images.githubusercontent.com/1899506/96470998-c77f5480-1226-11eb-9d4d-43738b0fb68d.png)

**Additional information**
The dropdown codeblock is:

`<div class="grouped-listing__dropdown"><form class="form form__select"><select aria-label="Jump to listing group"><option value="draft">Draft</option><option value="screening">Screening</option><option value="more-information-required">More information required</option><option value="dismissed">Dismissed</option><option value="accepted">Accepted</option></select></form></div>`

**Comment by frjo** [comment]
This is not so mush a filter as a quick jump menu.

**Comment by ei8fdb** [comment]
Hmm, that doesn't seem to work as it doesn't "jump" anywhere either!

**Comment by frjo** [comment]
For my selecting "Accepted" scrolls the left column so "Accepted" section is at the top.

**Comment by ei8fdb** [comment]
Hmm, OK so maybe there's a bug.

I'm using:
Firefox Developer 82.0b9 (64-bit)
Mac OS 10.15.6

**Comment by vimal1083** [comment]
I see the issue in firefox browser, Will fix this
