### ISSUE TITLE
If a user have staff and reviewer role they get an error when trying to submit review

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2151]

**Comment by vimal1083** [comment]
@frjo , I have created a new user with the staff and reviewer role in [https://dev-apply.opentech.fund/]. But I couldn't reproduce the error when I submit the review. So, could you help me with the steps to reproduce the error?. Below are the credentials of the new user

email : vimal2@yopmail.com
password : Vimaldev@123

**Comment by frjo** [comment]
This might have been an edge case or another bug, have not heard about it since. I will close this issue and then can report it again if needed.
