### ISSUE TITLE
Extend the Hypha style guide at "/styleguide"

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2152]
Make it on par with the Wagtail style guide "/admin/styleguide/"

**Comment by ei8fdb** [comment]
This would be *extremely* helpful for UX designers when doing design wireframes/prototypes.

**Comment by ei8fdb** [comment]
@frjo Where can this styleguide be accessed?

**Comment by frjo** [comment]
Need to deploy it first. This is only the bare minimum, will work on it when I have time.
