### ISSUE TITLE
On some submission not possible to set screening status, the table say "Awaiting". No thumbs on detail page.

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2182]
There seem to be a bug in the new screening system.

On the submission detail page some submissions do not show the thumbs and instead show a single status that you can't change.

**Comment by frjo** [comment]
I believe the issue is with submissions that have a screening status set since before. They say "Awaiting" in the submission list/table but look like this in detail view.

<img width="370" alt="Skärmavbild 2020-12-14 kl  07 35 52" src="https://user-images.githubusercontent.com/191392/102048289-286a7980-3ddf-11eb-8a71-093f9b9bf24d.png">

**Comment by sks444** [comment]
For an old submission, if a status is already set which is not default, we can not change that and we also won't be seeing the thumbs.

See last point at https://github.com/OpenTechFund/hypha/issues/2158#issuecomment-724497699
>When they have a screening status set which is not default...

Showing "Awaiting" for such submissions in the table is a bug.

We need to check [here](https://github.com/OpenTechFund/hypha/blob/39d88dc5eca53164b4612111212db08aad961536/hypha/apply/funds/tables.py#L143) if the submission has another status set which is not default and render accordingly.

**Comment by frjo** [comment]
@danblah So this can be fixed by adding a corresponding  default screening status to each submission. Should I go ahed a do that? Will preparer it in any case.
