### ISSUE TITLE
Website Internet Freedom Fund and Results Page

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#2188]
**Describe the bug**

1) The bullets appears on this page in WagTail, but not on the website.  https://www.opentech.fund/funds/internet-freedom-fund/

2) Data visualization is not being pulled onto the page anymore https://www.opentech.fund/results/impacts-and-outcomes. I believe this is where it is supposed to pull from: https://github.com/OpenTechFund/dataviz/tree/master/impacts — it used to appear on this page:

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- General public

**Desktop (please complete the following information):**

**Comment by frjo** [comment]
1. The current theme on OTF site is set to not show lists with bullets
