### ISSUE TITLE
Multiple proposal forms for Double stage funds do not show up on new stream form Determinations

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2204]
See PR https://github.com/OpenTechFund/hypha/pull/1412.

When setting multiple proposal forms on a Fund they do not show up when creating an determination to "Invite for proposal".

With the old hardcoded determinations forms a select widget with the proposal forms from the Fund show up. Allowing the staff to pick different proposal forms for different applications.

OTF needs this soon so if it can be fixed this week would be excellent.

**Comment by fourthletter** [comment]
I tested the feature and it worked for me. Thank you!

Test 1) https://test-apply.opentech.fund/apply/submissions/305/
As a manager, I was able to select one out of  **5** different proposals in the May 2021 Test Round
As an applicant, I received the correct application the manager assigned.

Test 2) https://test-apply.opentech.fund/apply/submissions/306/
During the second test, using the Multi proposal form test created by the dev team, I was only able to see **2** different proposals. 
As a manager, I was able to select one out of two different proposals.
As an applicant, I received the correction application the manager assigned.
