### ISSUE TITLE
Add category questions as filters on submission table view

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2206]
Add checkbox "Add to submission filter" to each category.

**Comment by frjo** [comment]
@Parbhat Can your tema take this over. I have made a start just to show what OTF want.

**Comment by Parbhat** [comment]
Yeah, will continue work on it.

**Comment by sks444** [comment]
To understand the requirements:

- So we want a field `use_for_submission_filter` in Category and if that is checked, those categories should come in the table for filtering submissions..is that correct?

@frjo, I see you also added an extra field `is_archived` could you explain what is that for?

**Comment by frjo** [comment]
Use case: OTF will add category questions to applications where applicants specify the type of project they are applying for. Staff will handle one or two types each so want to be able to filter on category in the submission table.

There are a lot of category questions so an option to pick the ones that show up in the filter helps making it less messy. We have this for meta terms already.

@sks444  The "is_archived" is to give staff the ability to "retire" category questions without deleting them. They should be visible on older submissions but not available on new applications. But this makes this PR unnecessary complicated I realise now so let us remove that part for now and do it in a separate PR.

And yes this should show in the React app as well. Meta terms so should be there as well but I do not know how to best cram that in on the width space available.

**Comment by sks444** [comment]
I am looking into this but the implementation doesn't seem to be as direct.

So as per the requirement, we need show all the category options(which have been chosen by applicant during application submission) as filter options in the submission table. And based on the selected filter/s we need to filter out the correct submissions.

What makes it a bit complex to implement is the fact that the [Category](https://github.com/OpenTechFund/hypha/blob/116469e6be608c7d3eae81afc0501e10f963702a/hypha/apply/categories/models.py#L21) model itself is not directly related to the submission like we have for [meta terms](https://github.com/OpenTechFund/hypha/blob/116469e6be608c7d3eae81afc0501e10f963702a/hypha/apply/funds/models/submissions.py#L440) and we need to do all the manipulation from submission form_data where all the chosen category options are being saved.

So to get the correct filter options from all category options, we need to iterate through all the submission and get the correct options from their form_data. But as the category field is created from a [stream field block](https://github.com/OpenTechFund/hypha/blob/116469e6be608c7d3eae81afc0501e10f963702a/hypha/apply/categories/blocks.py#L27) the name of it will also be not constant and will be in form of ids. So we will have to get all the category field ids from submission [form_fields](https://github.com/OpenTechFund/hypha/blob/116469e6be608c7d3eae81afc0501e10f963702a/hypha/apply/funds/models/submissions.py#L418) and then for those fields we need to get the correct options selected from form_data. This is to get all the options which are being used by a submissions to show as filter options. The same process will be followed to filter out a submission for the selected options.

I am just thinking on a better approach to do this. Will send in a pr soon. Let me know your views.

**Comment by frjo** [comment]
@sks444 Maybe the Category questions is the wrong solution to the need OTF has?

Is a new field type specifically built for this better?

1. It should be possible to add to application forms.
2. Show up as radio or checkboxes depending on if multi select is true or not.
3. Be possible to filter on in the submission table.

**Comment by sks444** [comment]
@frjo, implementing a whole new field just for this purpose may lead to an over-implementation, when there is one already existing.

I guess we are also using category questions at other places and had plan to use it [more](https://github.com/ResetNetwork/apply-app/issues/79). So it seems like we can keep this as a generic labelling system for the project.

That said, I will check the feasibility of both the options and move forward with which suits better.

**Comment by frjo** [comment]
Category questions is used for a number of questions on current application forms. See e.g. https://test-apply.opentech.fund/singleapplication-may-2021/

Focus, Status, Technology attributes, Objective(s), Beneficiaries, Region, Country and Addressed problems are all Category questions.

**Comment by sks444** [comment]
Thanks @frjo,

Have completed the first draft of this at https://github.com/OpenTechFund/hypha/pull/2210.

Let me know if that works, then we can add the same to api and then react interface.

Not sure why the tests are failing in the ci but passing locally. Checking on that..

**Comment by fourthletter** [comment]
I tested the filters on submission table view [https://test-apply.opentech.fund/apply/rounds/922/?category_options=327&per_page=&query=]

I was not able to filter submissions by categories. While I am able to see the categories in the drop down menu, the filter function does not work. 

Thanks.

**Comment by frjo** [comment]
This is due to use of non multi select category question. I'm deploying new code to test now that I believe fix this issue.

It will take a few minuts before it's active.

https://github.com/OpenTechFund/hypha/pull/2210/commits/5e4bdd47dc9f2019c53baded289561625c7d8497

**Comment by danblah** [comment]
Added and removed category groups to the dashboard. Tested filtering by one or more groups. All works as expected. This passes.

That said, this needs better specification > improvement. I'll immediately enable this for multiple categories making it a very useful but not-very-usable filter due to the larger number of items to scroll through (ie image adding countries + focus +  technology attributes).

Can we deploy this now but quickly add separator + header for each category used in the current long list or some other way to help quickly get to the actual category sought? I don't want to hold up OTF's need here.

My current thinking is to do this fully right, each category creates its own new filter option... ie Countries creates a new filter option for just countries, Focus for focuses, etc. Can we make an issue to do this as a more permanent solution?
