### ISSUE TITLE
Deleting wagtail pages leads to error in custom_wagtail_page_delete()

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2253]
This code was added in PR https://github.com/OpenTechFund/hypha/pull/1976 (https://github.com/OpenTechFund/hypha/issues/1971)

TypeError
'module' object is not callable

My guess is that Wagtail updated necessitate some updates to this code.

**Comment by frjo** [comment]
Adding a test for this would be nice so we do not miss the next time it change.

**Comment by Parbhat** [comment]
Yeah, but tracking internal changes is tricky. Usually major changes are mentioned in upgrade consideration section https://docs.wagtail.io/en/stable/releases/2.12.html#upgrade-considerations. We can have a wiki list of Wagtail overrides.
