### ISSUE TITLE
New generic field type to show more text on website

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#2254]
We are requesting a generic field type that folds out or reveals additional text when the user clicks on the heading.

We don’t want to show a long block of text on the website because 1) users only want to know more about their specific issue area of focus and 2) too much information will make the page text heavy. 

We believe that having text nested underneath a specific subject/heading would minimize the amount of text on the webpage at first glance.

**Comment by fourthletter** [comment]
Could you provide some prompts, links, or indicate how I could test this feature? Thank you.

**Comment by frjo** [comment]
@fourthletter  Add the new "More" field to any page in Wagtail admin. Each field has two rich text sections, the first always show, the other is reveled when users clicks a "Show more" button.

You can add as many "More" fields as you need to a page.

**Comment by fourthletter** [comment]
This works! Thank you! 💥
