### ISSUE TITLE
Revise "Duration" question in WagTail Application Forms 

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#2258]
We would like to use the "duration" question to ask "How long would this event or proposed activity will take?" The response will be in days. The response options are now only in weeks and months.

**Comment by frjo** [comment]
@fourthletter What day options would you need?

1, 2, 3, 4, 5, 6, 7

or more than that?

**Comment by fourthletter** [comment]
1, 2, 3, 4, 5, 6, 7 is good to start with. Thank you.
