### ISSUE TITLE
Assigning multiple leads within one fund

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/hypha#2271]
We will no longer have one lead overseeing a round, but multiple leads managing within each fund. Each lead will need to receive notifications and quickly access submissions (à la the dashboard?)

**Comment by danblah** [comment]
This has me thinking about a more general-purpose notification feature, allowing any manager to define notifications they receive based on criteria being met, for example:

If fund == IFF && Category Question: Focus == Privacy then notify me

If Category Question: Focus == Security && Cateogry Question: Country == Brazil then notify me

etc

**Comment by fourthletter** [comment]
This issue may no longer be necessary if we could develop #2161 for any user to receive notifications within Hypha.

**Comment by fourthletter** [comment]
This issue is no longer relevant and has been resolved.
