### ISSUE TITLE
Make content scollbars work in React app for Safari and Firefox

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/hypha#2284]
Would be good to make the React UI look and work the same on all popular browsers. It now only works correctly on Chromium based browsers it seems. Please add support for Safari and Firefox.

I believe fixing this will make https://github.com/OpenTechFund/hypha/pull/2283 work on all browsers as well.

![missing_scrollbars](https://user-images.githubusercontent.com/191392/111137977-b3dedc80-857f-11eb-9600-16b17e2e7254.png)

**Comment by vimal1083** [comment]
@frjo I got scrollbars in Firefox(version: Mozilla Firefox 86.0.1), checked on my ubuntu & mac. Could you share version of your mac & firefox?
![firefox-sidebar](https://user-images.githubusercontent.com/8245654/112434801-fe274100-8d69-11eb-9a72-b38cb1de9635.png)

**Comment by frjo** [comment]
Working for me as well now so closing this issue. Thanks for looking at it!
