### ISSUE TITLE
Add the ability for application, review, and determination forms to accept PGP encrypted text and then to be viewed by managers via Mailvelope

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#271]

**Comment by danblah** [comment]
I'm bumping this cause it's now more possible than before. See documentation for Encrypted Forms using Mailvelope available at https://github.com/mailvelope/mailvelope/wiki/files/Mailvelope-Encrypted-Form-Documentation.v1.2.0.pdf

@frjo and/or @Parbhat, could one of you review this document and provide a possible roadmap for us to accomplish this? I'm thinking something that initially involves a single streamfields plaintext form as an mvp to something more later.

**Comment by frjo** [comment]
https://github.com/mailvelope/mailvelope/wiki/files/Mailvelope-Encrypted-Form-Documentation.v1.2.0.pdf

**Comment by Parbhat** [comment]
Some notes after reading the Encrypted Forms documentation.

-  An important part of the process is Signing the form. The process of building a form is manual which requires secret OpenPGP key of the form data recipient (OTF). And form can be signed using GnuPG or Grunt javascript tool. Form immutability is a crucial part of the process. But our stream field forms allows creating forms dynamically. So, we will need to sign the form automatically when new fields are added to a form or a new form is created. We need to come up with another method other than described in the documentation for signing the form.

- Our current method of creating and validating forms needs updates. Currently, we create a 
block for the field and form field is generated based on the block type. Validation is performed both in front end and server-side. Django server-side validation needs to be turned off for fields. CSRF token can not be used as form should be immutable. So, the basic purpose of our application is to just accept the form's data. We have to implement the security consideration mentioned in the docs like Use the signature verification to prevent CSRF etc.

- Decrypting the data will probably need a new interface and implementation or the OTF staff can do it manually.

>The only limitation, as explained earlier, lies in the fact that there is no guarantee that the data
contained in the encrypted message is in the valid format and not malicious. With traditional
forms this validity check is performed using server side validation. With this solution this
responsibility is shifted to the client.

The simplest initial prototype would be to just host a signed HTML form which is created manually.
