### ISSUE TITLE
As a manager, I want to see the total number of concept notes and their total value within a defined time range, fund, etc

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#297]

**Comment by frjo** [comment]
@di @saoun @danblah  Test on https://test-apply.opentech.fund/apply/submissions/result/

Any other numbers you want calculated?

The look is very rudimentary but a designer can fix that if needed.

**Comment by fourthletter** [comment]
Test worked. We discussed changing the scope of this feature to query distinct dates of submissions. Example: Number of **concept notes** quested  within September 1, 2018 to September 30, 2018.

Question 1: Do these calculations include proposals as well? How does it distinguish between the same project that has submitted a concept note as well as a proposal? 

Question 2:What other categories or queries could we include in the results? For example, number of submissions or concept notes from a particular region.

**Comment by frjo** [comment]
@fourthletter It includes all proposals and concept notes that do not yet have a proposal linked to it.

I think the improvements to this feature is best in a new issue, then we can deploy what we have now and improve upon it in the coming weeks.
