### ISSUE TITLE
As a manager, I want a straightforward way to assign reviewers submission (team and ac) based on areas of specialism

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#300]

**Comment by danblah** [comment]
For mvp
1. At /account/, create a new area for "Interests"
1. Offer options to check all of the items in /admin/categories/category/
1. When auto assigning (https://github.com/OpenTechFund/opentech.fund/issues/613), attempt to match like submissions with like reviewers

**Comment by saoun** [comment]
i would add:
- allow reviewers (only) to select areas of interest, either at account creation, or in account page (when they click on their names)
- allow staff to assign area of interest to a reviewer

**Comment by fourthletter** [comment]
- allow reviewers the option to change their selected areas of interest 
- as a staff user I would like to **notify** reviewers that they've been matched with an application because it aligns with their area of interest or expertise
