### ISSUE TITLE
As an applicant, I'd like the ability create drafts of applications (and create an account, if required) 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#309]

**Comment by saoun** [comment]
This seems to be related to this https://github.com/OpenTechFund/opentech.fund/issues/308

I see it either as: 
- automatic saving as someone is going through the form (a la google docs)
- a floating save button, or one at the bottom next to submit

The draft would then appear in their dashboard the same way an application would.

**Comment by saoun** [comment]
related to this too https://github.com/OpenTechFund/hypha/issues/1874

**Comment by frjo** [comment]
@Parbhat My idea is to add a button on all (first stage) application (so all but proposal at this time) that say something like "Save as draft".

Clicking this would do all the same things as the "Submit for review" button does today. Create an account if needed, send out the same e-mails etc.

The only difference would be that the application state would be a new draft state. We already have "draft_proposal" so would need to add draft_* for the all the other.

When the applicant logged in and opens up the application that is is draft they still see the two buttons  "Submit for review" and "Save as draft".

They can continue to "Save as draft" until they hit  "Submit for review" for the first time. Then we are back to how it works now and the "Save as draft" are removed.

Does this sounds like it can work and something your team can take on?

**Comment by Parbhat** [comment]
@frjo Sounds like a good approach. Mostly we have to make changes in our workflow.py for the draft state. The default [status](https://github.com/OpenTechFund/hypha/blob/3601c9823de61320c2cb3b39d89d2a2aba7ad113/hypha/apply/funds/models/submissions.py#L422) is set as INITIAL_STATE so we will also take it into account while creating a submission for `Save as draft`. I can not see any roadblocks. We will work on it. Thanks for the detailed user workflow. Btw I also like this approach

>Allow for a client side caching of the application so that the user has access to their data in the form without logging-in (Pros: People don't need to create accounts; Cons: Users might assuming that this behavior is introducing security risks, also many users disable javascript for security reasons) - https://github.com/OpenTechFund/hypha/issues/1874#issue-586675893

Github also uses this in comments and helps sometimes to not lose content. But as said in issue, we also need to look into the implications of storing the sensitive data.

**Comment by rudietuesdays** [comment]
Hey @frjo @Parbhat ! @harumhelmy and I are happy to take this on starting today or tomorrow if that's helpful, but if work is already underway on it elsewhere please let us know.

**Comment by frjo** [comment]
@rudietuesdays I believe this is better suited for @Parbhat team that has worked a lot with both Django and Python. It involves the workflow that interacts with almost every other part of the app.

**Comment by fourthletter** [comment]
As a user I would like to save a draft without filling in all required fields in a concept note.

When drafting a proposal, applicants are currently required to fill in all required fields, then they can save. Referenced here: https://github.com/OpenTechFund/hypha/issues/1914#issuecomment-610288816

**Comment by frjo** [comment]
@saoun @fourthletter This is now on test for you to test.

I fell the draft button should be button number two and the "Submit for review" first. What do you think?

Should we have a short text below the buttons explain what happens when saving as draft?

**Comment by fourthletter** [comment]
Hi @bumbleblue -- checking to see if you have any insights about the UX.

**Comment by bumbleblue** [comment]
I think [Submit for review] (blue button) and then [Save as draft] (white) would be intuitive.

I would highlight the fact that applicants do not expect their drafts to be visible to the reviewers, so it'd be important to not display drafts in the web app in whatever shape or form. (I'm sure that's intended, but I wanted to reiterate!)

Also tagging @ei8fdb who's leading the UI work here!

**Comment by frjo** [comment]
@bumbleblue @fourthletter Draft submission is as far as I know invisible to all but the applicant who submitted it. Do you have examples of where this is not the case? (Admins can of course see it directly in the DB so it not a real secret.)

**Comment by fourthletter** [comment]
@frjo 

- Draft submissions are invisible to all but the applicant who submitted it.

- first button as [Submit for review] (blue button) and then second button [Save as draft] (white) sounds good.

- I don't think we need any short text below the buttons to explain what happens when saving a draft.

**Comment by fourthletter** [comment]
It's beautiful. Thank you!

![image](https://user-images.githubusercontent.com/20019656/83637785-27c27200-a576-11ea-856a-bec8ae471f35.png)

**Comment by frjo** [comment]
@fourthletter Have you tested the workflow from an applicants and a staffs perspective.

This is a new function directly for applicants and it's important that it works smoothly or applicants will take a dislike for it.

**Comment by fourthletter** [comment]
I provided the system with a 12 word password but caused a breech. I requested a password reset and received a new link. I attempted to create another 12 word password, but caused another breech.

![image](https://user-images.githubusercontent.com/20019656/83638790-b2f03780-a577-11ea-8089-a60269b4a087.png)


Applicants receive this email: 
![image](https://user-images.githubusercontent.com/20019656/83638663-7e7c7b80-a577-11ea-8045-3b485cda17de.png)

**Comment by frjo** [comment]
@fourthletter That warning tells you that the password you tried to set is a bad choice. It was used by one of the many millions of accounts that have been part of mayor security breaches. 

We use an API from this service https://haveibeenpwned.com/.

**Comment by frjo** [comment]
We only really have two rules regarding passwords, they must be at least 12 characters and they can not have been part of a breach.

No nonsense about big and small letters etc or resetting the password every x days.

**Comment by fourthletter** [comment]
Test complete. Thank you.
