### ISSUE TITLE
As an applicant, for each form element on an application, I'd like the ability quickly view links to more information, ask for help if I don't understand the question, and provide feedback on how to improve the question.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#329]

**Comment by fourthletter** [comment]
Relates to #711  #338  #339

**Comment by danblah** [comment]
I like the idea of having a small (i) or (?) icon for each form element that on hover or click provides box with:

* a link to the relevant section at guide.opentech.fund
* option to ask for help
* option to provide suggestions on how to improve the question
