### ISSUE TITLE
Ability to have forms with multiple pages, field groups with headers, and conditional fields based on earlier choices

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#573]

**Comment by frjo** [comment]
@danblah Headers for groups of fields is already possible. Use the "Paragraph" field that is listed in "Other" when you edit an application form.

**Comment by danblah** [comment]
https://github.com/OpenTechFund/opentech.fund/issues/1163 and the group fields function are more what this is referring to.
