### ISSUE TITLE
Allow application form makers to set word counts for text fields and then display how many words are left to applicants

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#577]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/OpenTechFund/opentech.fund/issues/577)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars1.githubusercontent.com/u/620336?v=4' alt='danblah' width=24 height=24> danblah](https://issuehunt.io/u/danblah) ($50.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/OpenTechFund/opentech.fund/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by fourthletter** [comment]
Related to #705

**Comment by georgiamoon** [comment]
This came up in our interviews as well, FYI!

**Comment by bumbleblue** [comment]
The feedback we received from applicants is that nobody wants a "hard" word limit, because there's always encoding or formatting issues with character counts. A soft word limit could be something that throws off a warning upon submission, e.g. "You're 40% over the recommended word count!"

**Comment by fourthletter** [comment]
All acceptance criteria was visible and functional. Thank you! 💥 

![image](https://user-images.githubusercontent.com/20019656/80372678-e269a100-8861-11ea-8082-a579f751ae52.png)
