### ISSUE TITLE
On the projects listing page, list only the active projects sorted newest to oldest by default and bring back the filters we had on the old site

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#639]
See https://archive.opentech.fund/projects for examples on the filters

Filters included:

- Status (Currently being funded or a previously funded project)
- Core issues
- Objectives
- Beneficiaries
- Addressed problems
- Technology focus
- Regions
- Funding range (was a slider on the old site)

**Comment by danblah** [comment]
See #640, would be great if we could combine these listings

**Comment by fourthletter** [comment]
Relates to filters and meta tags #973 #972 #550
