### ISSUE TITLE
For each fund or lab, add a field in the form for the guide url. If exist, display a button on the fund/lab page as well as the application with link.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#695]

**Comment by tmsndrs** [comment]
UX Tasks
- [ ] Mockup UI

**Comment by tmsndrs** [comment]
I should add that the button on the form page is sticky, like the apply button elsewhere on the site.

**Comment by todd-dembrey** [comment]
as discussed with @tmsndrs:

The application guide button will link to the specific page within the guide for that fund. There will be a new field on the public page to allow the admin to point to the correct page.

The alternative is linking to a more generic landing page for the guide and allowing the User to navigate from there. 

Perhaps we need a better link to the guide across the site generally?

**Comment by danblah** [comment]
See all the other tickets with the label guide as well

**Comment by frjo** [comment]
@danblah Is this needed on top of the per field help links?

**Comment by fourthletter** [comment]
@frjo Are you asking whether each field will need a help link/button to the guide url? Or where the button should appear on the application? Or a completely different question...

**Comment by frjo** [comment]
@fourthletter The help link per field is a done deal and will get deployed soon.

The question is about the need for a help link for the page/form on top of that.

**Comment by frjo** [comment]
@saoun This is now on test for testing. I have added one example at this fund, https://test-apply.opentech.fund/admin/pages/726/edit/

The resulting application guide link/button can be seen here:

* https://test.opentech.fund/funds/rapid-response-fund/ (the public fund page)
* https://test-apply.opentech.fund/rapid-response-fund/ (the application form)

So you add the guide link on the fund or lab and it shows up on the public page and the application form for the fund or lab.
