### ISSUE TITLE
Create a tool to help people understand if they can get funding and which fund might be best for them

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#697]

**Comment by fourthletter** [comment]
Applicants are interested in learning:
•	Which type of projects have OTF supported? 
•	Where has OTF supported? What has been geographic trend from 2012 to 2019?
•	What is amount of OTF resources in region?
•	Likelihood of supporting new project vs. continuing support
•	What was last year’s focus? Will this trend continue in 2019?
•	Has funding supported an emergent issue or responded to community needs in a timely manner?
•	How has projected impacted region?
•	Unfunded projects are given feedback and adequate information to develop successful proposals
•	Is there a stepping stone or link between various OTF funding streams?

**Comment by fourthletter** [comment]
Relates to #251
