### ISSUE TITLE
Provide indicative information to applicants about length of process

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#708]

**Comment by tmsndrs** [comment]
![application-process](https://user-images.githubusercontent.com/7290588/48724343-e4691280-ec20-11e8-84a8-e3d90f8cbbde.png)

Mock-up for application process including length of phases.

**Comment by todd-dembrey** [comment]
I like the concept and repetition of the progress bar pattern used within the application system.

It does feel like a duplication of some of the content within the guide but i don't think that cant be helped.

I am curious about how this would look on mobile. Would a vertical approach without scroll be better?

Is this specific to the workflow or would we want to make this custom for the fund?

**Comment by tmsndrs** [comment]
I think it would need to be custom to the fund.

It's almost identical to the content in the guide but the point is to make it move visual and pull it out to where people are more likely to see it. 

On mobile I was just thinking it would be a case of scrolling sideways. Vertical would make the page very long.

**Comment by danblah** [comment]
Do you think we could make a mockup of this for each workflow type, which could then automatically show up on the fund page based on the associated workflow?

**Comment by danblah** [comment]
Dup of #318

**Comment by danblah** [comment]
See #318. A function looks back 180 days for the given fund/lab to calculate the average time from submission to approval or dismissal and presentes that on the fund/lab page.

**Comment by fourthletter** [comment]
Please @bumbleblue let us know what you have any insights about this issue. Thank you!
