### ISSUE TITLE
API: Tests

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/hypha#879]
Tests for all implemented API endpoints

**Comment by todd-dembrey** [comment]
This is in progress and can be tracked at #1156

**Comment by danblah** [comment]
@frjo, can you update us here on this?

**Comment by saoun** [comment]
@frjo status on this? anything to be done?

**Comment by frjo** [comment]
This is still relevant. The PR #1156 ads some test and also put a version number, i.e. "api.opentech.fund/v1/", in to the api calls. This is needed before we do anything serious with the api.

With version api calls it's possible to have two or more api versions in parallel. You can keep version v1 while developing v2 ant not break everything that uses v1.

**Comment by saoun** [comment]
so is this something we can deploy? or are we waiting on something? I don't seem to see anything holding this back

**Comment by frjo** [comment]
Since Todd makes it WIP (work in progress) I assume it's not done yet.

**Comment by todd-dembrey** [comment]
The changes to use a versioned API are probably good to go, what is lacking are some tests for the API which was the scope of this ticket. I think someone can merge #1156 which in its current form is more to do with #880 about how the API documents are structured. And update the backlog to add some tests to this area?

**Comment by saoun** [comment]
@frjo is this something you can do ?

**Comment by frjo** [comment]
Rebased the PR now and if it passes test I will be in the next deploy.
