### ISSUE TITLE
API: Deployment and config

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/hypha#880]
Deployment, configuration and tidy up of where files live

**Comment by gibbsmaya** [comment]
This has been deployed as part of Winter Sprints work, however keeping this open as would be nice to revisit this and tidy up files etc.

**Comment by todd-dembrey** [comment]
This has been started as part of #1156 

I have broken the API out into `/api/v1`. This does not cover the potential change of using `api.opentech.fund` but does make a start by separating out the urls. @frjo FYI

**Comment by danblah** [comment]
@frjo, can you update us on this?

**Comment by saoun** [comment]
@frjo status on this? anything to be done?

**Comment by frjo** [comment]
See https://github.com/OpenTechFund/opentech.fund/issues/879#issuecomment-577050990

**Comment by todd-dembrey** [comment]
see https://github.com/OpenTechFund/hypha/issues/879#issuecomment-581972576 for update - propose close this ticket with changes from #1156 and write tests for API based on work from#1156.
