### ISSUE TITLE
If a fund specific slack channel is defined and the slack bot is not in the defined channel, do something to let the team know they need to invite the bot to the defined channel or have the bot autojoin the channel if possible

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#943]
This could be an @channel alert in the channel or a pm to the fund lead or both?

**Comment by frjo** [comment]
@jheretic Would it be possible to get "botf" to auto join a new Slack channel?

Or send an alert to another channel that it needs to be invited to channel x?

**Comment by frjo** [comment]
@jheretic Ping

**Comment by danblah** [comment]
@jheretic double ping!

**Comment by saoun** [comment]
@jheretic ping on this! is this something you can work on?

**Comment by jheretic** [comment]
Yes, sorry I've let some of the Hyfa stuff slide due to other commitments. Rae and I will be pitching back in on this, and I'll take a look at this shortly.
