### ISSUE TITLE
Create an API endpoint for submission meta data, that includes fields in Meta (including screening status), and terms in Apply>Category Questions

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/hypha#973]

**Comment by danblah** [comment]
Fields to include:
* Submission/Application/Node ID
* Workflow state
* Screening status
* All Apply>Meta categories
* All Apply>Category Questions (Descriptors)
* Amount requested
* Duration
* Region
* Every applied before
* Country of the applicant
* Country of focus
* Request/Fund
* Round
* Lead
* Reviewers
* Date of submission
* Date of the first review
* Date of first determination
* Date of the first comment
* Total number of determinations
* Total number of reviews
* Total number of comments
* Total number of revisions
* Total number of past submissions

Allows a query by as many of the above fields as possible. mvp is date range of submission, region, country, specific ID, and request/fund id.

**Comment by danblah** [comment]
Please update this to reflect reality ;-)

## Endpoints
### Submissions (meta)
**GET /submissions/?{query parameters}/meta**

**Query:**
* time{period parameter} - Filters to submissions by specified date range
    * 'time=RANGE&from=YYYY-MM-DD&to=YYYY-MM-DD`
    * 'time=24HRS'
    * 'time=LAST_7_DAYS'
    * 'time=THIS_MONTH'
    * 'time=LAST_MONTH'
    * 'time=LAST_14_DAYS'
    * 'time=LAST_30_DAYS'
    * 'time=LAST_60_DAYS'

* round - Filters to submissions by specified round, allows multiple
* region - Filters submissions by specified region of focus, allows multiple
* country - Filters submissions by specified country of focus, allows multiple
* fund - Filters submissions by specified fund and lab, allows multiple
* tags - All Apply>Meta categories, allows multiple
* discriptors - All Apply>Category Questions (Descriptors), allows multiple
* amount=RANGE&high={int]&low={int}

Returns: 
Array of matching JSON objects, containing the parameters listed above. Returns an empty array if there are no matches.
* List of JSON objects
    * Submission/Application/Node ID
    * Workflow state
    * Screening status
    * All Apply>Meta categories
    * All Apply>Category Questions (Descriptors)
    * Amount requested
    * Duration
    * Region
    * Ever applied before
    * Country of the applicant
    * Country of focus
    * Request/Fund
    * Round
    * Lead
    * Reviewers
    * Date of submission
    * Date of the first review
    * Date of first determination
    * Date of the first comment
    * Total number of determinations
    * Total number of reviews
    * Total number of comments
    * Total number of revisions
    * Total number of past submissions
    * Associated submission
    * Average review score
    * List of review outcomes

### Submission (meta)
**GET /submission/{id}/meta**

Returns: 
Array of matching JSON objects, containing the parameters listed above. Returns an empty array if there are no matches.
* List of JSON objects
    * Submission/Application/Node ID
    * Workflow state
    * Screening status
    * All Apply>Meta categories
    * All Apply>Category Questions (Descriptors)
    * Amount requested
    * Duration
    * Region
    * Ever applied before
    * Country of the applicant
    * Country of focus
    * Request/Fund
    * Round
    * Lead
    * Reviewers
    * Date of submission
    * Date of the first review
    * Date of first determination
    * Date of the first comment
    * Total number of determinations
    * Total number of reviews
    * Total number of comments
    * Total number of revisions
    * Total number of past submissions
    * Associated submission
    * Average review score
    * List of review outcomes

**Comment by newbie15423** [comment]
I can't tell what the All Apply> includes but should be Status (Just an idea..), Focus (privacy, access), technology attributes, objective and addressed problems. Also we should definitely have whether it was invited to proposal or not, can't tell if that is part of list of review outcomes.

**Comment by fourthletter** [comment]
Relates to filters and meta tags #972 #639 #550

**Comment by Parbhat** [comment]
@danblah @frjo I was relating this issue to Meta categories but looking into it closely today it looks like related to metadata about submissions. And that metadata can be fields on the submission model and other computed data. Is this correct? If yes, do we need new API endpoints? There are already API endpoints available which can be extended. For example, submissions list [endpoint](https://github.com/OpenTechFund/opentech.fund/blob/f9bfd193b822cdfc949dad5ea22e8fa7774b1d85/opentech/apply/funds/api_views.py#L59) is `/apply/api/submissions/` which list all submissions and allows to filter by round, status and active (filter by active gives error currently). This API endpoint can be extended to filter by region, tags etc. The returned data is minimal and detailed data can be accessed with detail endpoint of submission. Similarly submission detail [endpoint](https://github.com/OpenTechFund/opentech.fund/blob/f9bfd193b822cdfc949dad5ea22e8fa7774b1d85/opentech/apply/funds/api_views.py#L70) `/apply/api/submissions/<id>/` can return more metadata like lead, reviewers, date of the first review etc. 

More details about the requirement would be great to evaluate options.

**Comment by danblah** [comment]
Thats right, we're on the same page... extend the existing endpoints to return the above and filter by the above.

**Comment by Parbhat** [comment]
Great

**Comment by Parbhat** [comment]
@danblah @fourthletter Can you please review the current endpoints `/apply/api/submissions/` and `/apply/api/submissions/<ID>/`? And update the issue with the required new fields and modifications.

@frjo Do you know how to get the region of a submission? Searching through the codebase, in`apply/categories/categories_seed.py` Regions are created as a category. And the category is included as [CategoryQuestionBlock](https://github.com/OpenTechFund/opentech.fund/blob/25b75ef56248825a89d4d8eb671c06336cee7a89/opentech/apply/funds/blocks.py#L171) in application forms. Is it correct?

> region - Filters submissions by specified region of focus, allows multiple

**Comment by frjo** [comment]
@Parbhat Yes that is correct, Categories are stored as stream fields on submission. That means they are "buried" in field_data json blob.

**Comment by Parbhat** [comment]
@frjo Thanks. Json data makes it a bit tricky to implement filtering.

**Comment by frjo** [comment]
@Parbhat Do it for the meta categories first.

I believe we will need to merge the Categories questions in to meta categories. The problem then is how to make it nice and easy for the applicant to set them.

**Comment by frjo** [comment]
@danblah @fourthletter @saoun Please see @Parbhat questions above in https://github.com/OpenTechFund/opentech.fund/issues/973#issuecomment-510803941
